//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace NTST.ScriptLinkService.Web.ClientDischarge {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientDischargeSoap", Namespace="http://tempuri.org")]
    public partial class ClientDischarge : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DischargeClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientDischarge() {
            this.Url = global::NTST.ScriptLinkService.Web.Properties.Settings.Default.NTST_ScriptLinkService_Web_ClientDischarge_ClientDischarge;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DischargeClientCompletedEventHandler DischargeClientCompleted;
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientDischarge.DischargeClient", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse DischargeClient(string SystemCode, string UserName, string Password, ClientDischargeObject ClientDischargeInfo, string ClientID, string EpisodeNumber) {
            object[] results = this.Invoke("DischargeClient", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientDischargeInfo,
                        ClientID,
                        EpisodeNumber});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DischargeClientAsync(string SystemCode, string UserName, string Password, ClientDischargeObject ClientDischargeInfo, string ClientID, string EpisodeNumber) {
            this.DischargeClientAsync(SystemCode, UserName, Password, ClientDischargeInfo, ClientID, EpisodeNumber, null);
        }
        
        /// <remarks/>
        public void DischargeClientAsync(string SystemCode, string UserName, string Password, ClientDischargeObject ClientDischargeInfo, string ClientID, string EpisodeNumber, object userState) {
            if ((this.DischargeClientOperationCompleted == null)) {
                this.DischargeClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDischargeClientOperationCompleted);
            }
            this.InvokeAsync("DischargeClient", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientDischargeInfo,
                        ClientID,
                        EpisodeNumber}, this.DischargeClientOperationCompleted, userState);
        }
        
        private void OnDischargeClientOperationCompleted(object arg) {
            if ((this.DischargeClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DischargeClientCompleted(this, new DischargeClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientDischarge.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ClientDischargeObject {
        
        private string arrests30DayPriorDiscField;
        
        private string discEmploymentStatusField;
        
        private string accompaniedByField;
        
        private string aliasField;
        
        private string alias10Field;
        
        private string alias2Field;
        
        private string alias3Field;
        
        private string alias4Field;
        
        private string alias5Field;
        
        private string alias6Field;
        
        private string alias7Field;
        
        private string alias8Field;
        
        private string alias9Field;
        
        private string citizenshipField;
        
        private string clientAddressCityField;
        
        private string clientAddressCountryField;
        
        private string clientAddressCountyField;
        
        private string clientAddressStateField;
        
        private string clientAddressStreetField;
        
        private string clientAddressStreet2Field;
        
        private string clientAddressZipcodeField;
        
        private string clientCellPhoneField;
        
        private string clientConfAddressCityField;
        
        private string clientConfAddressCountryField;
        
        private string clientConfAddressStateField;
        
        private string clientConfAddressStreetField;
        
        private string clientConfAddressStreet2Field;
        
        private string clientConfAddressZipcodeField;
        
        private string clientConfPhoneNumberField;
        
        private string clientEmailAddressField;
        
        private string clientHomePhoneField;
        
        private string clientLivingArrangementField;
        
        private string clientMailAddressCityField;
        
        private string clientMailAddressCountryField;
        
        private string clientMailAddressStateField;
        
        private string clientMailAddressStreetField;
        
        private string clientMailAddressStreet2Field;
        
        private string clientMailAddressZipcodeField;
        
        private string clientRaceField;
        
        private string clientWorkPhoneField;
        
        private string communicationPreferenceField;
        
        private string countryOfOriginField;
        
        private string currentResCodeField;
        
        private System.DateTime dateOfDeathField;
        
        private bool dateOfDeathFieldSpecified;
        
        private System.DateTime dateOfDischargeField;
        
        private bool dateOfDischargeFieldSpecified;
        
        private string dischargePractitionerField;
        
        private string dischargeReferralTypeField;
        
        private string dischargeRemarksField;
        
        private string dischargeTimeField;
        
        private string educationField;
        
        private string employmentStatusField;
        
        private string ethnicOriginField;
        
        private string homelessIndicatorField;
        
        private string hospitalInstructionsField;
        
        private string maritalStatusField;
        
        private string occupationField;
        
        private string otherEthnicOriginsField;
        
        private string otherRacesField;
        
        private string placeOfBirthField;
        
        private string preferredProvidersEthnicOriginField;
        
        private string preferredProvidersSexField;
        
        private string primPresentingProblemField;
        
        private string primaryLanguageField;
        
        private string reasonForDeathField;
        
        private string religionField;
        
        private System.DateTime sSDemographicsDate1Field;
        
        private bool sSDemographicsDate1FieldSpecified;
        
        private System.DateTime sSDemographicsDate2Field;
        
        private bool sSDemographicsDate2FieldSpecified;
        
        private System.DateTime sSDemographicsDate3Field;
        
        private bool sSDemographicsDate3FieldSpecified;
        
        private System.DateTime sSDemographicsDate4Field;
        
        private bool sSDemographicsDate4FieldSpecified;
        
        private System.DateTime sSDemographicsDate5Field;
        
        private bool sSDemographicsDate5FieldSpecified;
        
        private string sSDemographicsDict1Field;
        
        private string sSDemographicsDict10Field;
        
        private string sSDemographicsDict2Field;
        
        private string sSDemographicsDict3Field;
        
        private string sSDemographicsDict4Field;
        
        private string sSDemographicsDict5Field;
        
        private string sSDemographicsDict6Field;
        
        private string sSDemographicsDict7Field;
        
        private string sSDemographicsDict8Field;
        
        private string sSDemographicsDict9Field;
        
        private string sSDemographicsFreeText201Field;
        
        private string sSDemographicsFreeText202Field;
        
        private string sSDemographicsFreeText203Field;
        
        private string sSDemographicsFreeText204Field;
        
        private string sSDemographicsFreeText205Field;
        
        private string sSDemographicsFreeText401Field;
        
        private string sSDemographicsFreeText402Field;
        
        private string sSDemographicsFreeText403Field;
        
        private string sSDemographicsFreeText404Field;
        
        private string sSDemographicsFreeText405Field;
        
        private string sSDemographicsMult1Field;
        
        private string sSDemographicsMult2Field;
        
        private string sSDemographicsMult3Field;
        
        private string sSDemographicsMult4Field;
        
        private string sSDemographicsMult5Field;
        
        private string sSDemographicsPhone1Field;
        
        private string sSDemographicsPhone2Field;
        
        private string sSDemographicsPhone3Field;
        
        private string sSDemographicsPhone4Field;
        
        private string sSDemographicsPhone5Field;
        
        private string sSDemographicsPractitioner1Field;
        
        private string sSDemographicsPractitioner2Field;
        
        private string sSDemographicsPractitioner3Field;
        
        private string sSDemographicsPractitioner4Field;
        
        private string sSDemographicsPractitioner5Field;
        
        private string sSDemographicsScrollFreeText1Field;
        
        private string sSDemographicsScrollFreeText2Field;
        
        private string sSDemographicsScrollFreeText3Field;
        
        private string sSDemographicsScrollFreeText4Field;
        
        private string sSDemographicsScrollFreeText5Field;
        
        private string sSDemographicsTime1Field;
        
        private string sSDemographicsTime2Field;
        
        private string sSDemographicsTime3Field;
        
        private string sSDemographicsTime4Field;
        
        private string sSDemographicsTime5Field;
        
        private string sSDischAdmFreeTxt20fiveField;
        
        private string sSDischAdmFreeTxt20fourField;
        
        private string sSDischAdmFreeTxt20oneField;
        
        private string sSDischAdmFreeTxt20threeField;
        
        private string sSDischAdmFreeTxt20twoField;
        
        private string sSDischAdmFreeTxt40fiveField;
        
        private string sSDischAdmFreeTxt40fourField;
        
        private string sSDischAdmFreeTxt40oneField;
        
        private string sSDischAdmFreeTxt40threeField;
        
        private string sSDischAdmFreeTxt40twoField;
        
        private System.DateTime sSDischargeAdmDate1Field;
        
        private bool sSDischargeAdmDate1FieldSpecified;
        
        private System.DateTime sSDischargeAdmDate2Field;
        
        private bool sSDischargeAdmDate2FieldSpecified;
        
        private System.DateTime sSDischargeAdmDate3Field;
        
        private bool sSDischargeAdmDate3FieldSpecified;
        
        private System.DateTime sSDischargeAdmDate4Field;
        
        private bool sSDischargeAdmDate4FieldSpecified;
        
        private System.DateTime sSDischargeAdmDate5Field;
        
        private bool sSDischargeAdmDate5FieldSpecified;
        
        private string sSDischargeAdmDict1Field;
        
        private string sSDischargeAdmDict2Field;
        
        private string sSDischargeAdmDict3Field;
        
        private string sSDischargeAdmDict4Field;
        
        private string sSDischargeAdmDict5Field;
        
        private string sSDischargeAdmDict6Field;
        
        private string sSDischargeAdmDict7Field;
        
        private string sSDischargeAdmDict8Field;
        
        private string sSDischargeAdmDict9Field;
        
        private string sSDischargeAdmFreeTxt1Field;
        
        private string sSDischargeAdmFreeTxt2Field;
        
        private string sSDischargeAdmFreeTxt3Field;
        
        private string sSDischargeAdmFreeTxt4Field;
        
        private string sSDischargeAdmFreeTxt5Field;
        
        private string sSDischargeAdmMult1Field;
        
        private string sSDischargeAdmMult2Field;
        
        private string sSDischargeAdmStaff1Field;
        
        private string sSDischargeAdmStaff2Field;
        
        private string sSDischargeAdmStaff3Field;
        
        private string sSDischargeAdmStaff4Field;
        
        private string sSDischargeAdmStaff5Field;
        
        private string sSDischargeAdmTime1Field;
        
        private string sSDischargeAdmTime2Field;
        
        private string sSDischargeAdmTime3Field;
        
        private string sSDischargeAdmTime4Field;
        
        private string sSDischargeAdmTime5Field;
        
        private string secPresentingProblemField;
        
        private string tertPresentingProblemField;
        
        private string typeOfDischargeField;
        
        private string policyNumber1Field;
        
        private string guarantor1Field;
        
        private string policyNumber2Field;
        
        private string guarantor2Field;
        
        private string policyNumber3Field;
        
        private string guarantor3Field;
        
        private string policyNumber4Field;
        
        private string guarantor4Field;
        
        private string policyNumber5Field;
        
        private string guarantor5Field;
        
        private string policyNumber6Field;
        
        private string guarantor6Field;
        
        private string policyNumber7Field;
        
        private string guarantor7Field;
        
        private string policyNumber8Field;
        
        private string guarantor8Field;
        
        private string policyNumber9Field;
        
        private string guarantor9Field;
        
        private string policyNumber10Field;
        
        private string guarantor10Field;
        
        /// <remarks/>
        public string Arrests30DayPriorDisc {
            get {
                return this.arrests30DayPriorDiscField;
            }
            set {
                this.arrests30DayPriorDiscField = value;
            }
        }
        
        /// <remarks/>
        public string DiscEmploymentStatus {
            get {
                return this.discEmploymentStatusField;
            }
            set {
                this.discEmploymentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string AccompaniedBy {
            get {
                return this.accompaniedByField;
            }
            set {
                this.accompaniedByField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Alias10 {
            get {
                return this.alias10Field;
            }
            set {
                this.alias10Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias2 {
            get {
                return this.alias2Field;
            }
            set {
                this.alias2Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias3 {
            get {
                return this.alias3Field;
            }
            set {
                this.alias3Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias4 {
            get {
                return this.alias4Field;
            }
            set {
                this.alias4Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias5 {
            get {
                return this.alias5Field;
            }
            set {
                this.alias5Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias6 {
            get {
                return this.alias6Field;
            }
            set {
                this.alias6Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias7 {
            get {
                return this.alias7Field;
            }
            set {
                this.alias7Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias8 {
            get {
                return this.alias8Field;
            }
            set {
                this.alias8Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias9 {
            get {
                return this.alias9Field;
            }
            set {
                this.alias9Field = value;
            }
        }
        
        /// <remarks/>
        public string Citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCity {
            get {
                return this.clientAddressCityField;
            }
            set {
                this.clientAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCountry {
            get {
                return this.clientAddressCountryField;
            }
            set {
                this.clientAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCounty {
            get {
                return this.clientAddressCountyField;
            }
            set {
                this.clientAddressCountyField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressState {
            get {
                return this.clientAddressStateField;
            }
            set {
                this.clientAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressStreet {
            get {
                return this.clientAddressStreetField;
            }
            set {
                this.clientAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressStreet2 {
            get {
                return this.clientAddressStreet2Field;
            }
            set {
                this.clientAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressZipcode {
            get {
                return this.clientAddressZipcodeField;
            }
            set {
                this.clientAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCellPhone {
            get {
                return this.clientCellPhoneField;
            }
            set {
                this.clientCellPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressCity {
            get {
                return this.clientConfAddressCityField;
            }
            set {
                this.clientConfAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressCountry {
            get {
                return this.clientConfAddressCountryField;
            }
            set {
                this.clientConfAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressState {
            get {
                return this.clientConfAddressStateField;
            }
            set {
                this.clientConfAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressStreet {
            get {
                return this.clientConfAddressStreetField;
            }
            set {
                this.clientConfAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressStreet2 {
            get {
                return this.clientConfAddressStreet2Field;
            }
            set {
                this.clientConfAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressZipcode {
            get {
                return this.clientConfAddressZipcodeField;
            }
            set {
                this.clientConfAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfPhoneNumber {
            get {
                return this.clientConfPhoneNumberField;
            }
            set {
                this.clientConfPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientEmailAddress {
            get {
                return this.clientEmailAddressField;
            }
            set {
                this.clientEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientHomePhone {
            get {
                return this.clientHomePhoneField;
            }
            set {
                this.clientHomePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ClientLivingArrangement {
            get {
                return this.clientLivingArrangementField;
            }
            set {
                this.clientLivingArrangementField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressCity {
            get {
                return this.clientMailAddressCityField;
            }
            set {
                this.clientMailAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressCountry {
            get {
                return this.clientMailAddressCountryField;
            }
            set {
                this.clientMailAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressState {
            get {
                return this.clientMailAddressStateField;
            }
            set {
                this.clientMailAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressStreet {
            get {
                return this.clientMailAddressStreetField;
            }
            set {
                this.clientMailAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressStreet2 {
            get {
                return this.clientMailAddressStreet2Field;
            }
            set {
                this.clientMailAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressZipcode {
            get {
                return this.clientMailAddressZipcodeField;
            }
            set {
                this.clientMailAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientRace {
            get {
                return this.clientRaceField;
            }
            set {
                this.clientRaceField = value;
            }
        }
        
        /// <remarks/>
        public string ClientWorkPhone {
            get {
                return this.clientWorkPhoneField;
            }
            set {
                this.clientWorkPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CommunicationPreference {
            get {
                return this.communicationPreferenceField;
            }
            set {
                this.communicationPreferenceField = value;
            }
        }
        
        /// <remarks/>
        public string CountryOfOrigin {
            get {
                return this.countryOfOriginField;
            }
            set {
                this.countryOfOriginField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentResCode {
            get {
                return this.currentResCodeField;
            }
            set {
                this.currentResCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfDeath {
            get {
                return this.dateOfDeathField;
            }
            set {
                this.dateOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfDeathSpecified {
            get {
                return this.dateOfDeathFieldSpecified;
            }
            set {
                this.dateOfDeathFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfDischarge {
            get {
                return this.dateOfDischargeField;
            }
            set {
                this.dateOfDischargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfDischargeSpecified {
            get {
                return this.dateOfDischargeFieldSpecified;
            }
            set {
                this.dateOfDischargeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DischargePractitioner {
            get {
                return this.dischargePractitionerField;
            }
            set {
                this.dischargePractitionerField = value;
            }
        }
        
        /// <remarks/>
        public string DischargeReferralType {
            get {
                return this.dischargeReferralTypeField;
            }
            set {
                this.dischargeReferralTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DischargeRemarks {
            get {
                return this.dischargeRemarksField;
            }
            set {
                this.dischargeRemarksField = value;
            }
        }
        
        /// <remarks/>
        public string DischargeTime {
            get {
                return this.dischargeTimeField;
            }
            set {
                this.dischargeTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Education {
            get {
                return this.educationField;
            }
            set {
                this.educationField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentStatus {
            get {
                return this.employmentStatusField;
            }
            set {
                this.employmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string EthnicOrigin {
            get {
                return this.ethnicOriginField;
            }
            set {
                this.ethnicOriginField = value;
            }
        }
        
        /// <remarks/>
        public string HomelessIndicator {
            get {
                return this.homelessIndicatorField;
            }
            set {
                this.homelessIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string HospitalInstructions {
            get {
                return this.hospitalInstructionsField;
            }
            set {
                this.hospitalInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string OtherEthnicOrigins {
            get {
                return this.otherEthnicOriginsField;
            }
            set {
                this.otherEthnicOriginsField = value;
            }
        }
        
        /// <remarks/>
        public string OtherRaces {
            get {
                return this.otherRacesField;
            }
            set {
                this.otherRacesField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredProvidersEthnicOrigin {
            get {
                return this.preferredProvidersEthnicOriginField;
            }
            set {
                this.preferredProvidersEthnicOriginField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredProvidersSex {
            get {
                return this.preferredProvidersSexField;
            }
            set {
                this.preferredProvidersSexField = value;
            }
        }
        
        /// <remarks/>
        public string PrimPresentingProblem {
            get {
                return this.primPresentingProblemField;
            }
            set {
                this.primPresentingProblemField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryLanguage {
            get {
                return this.primaryLanguageField;
            }
            set {
                this.primaryLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonForDeath {
            get {
                return this.reasonForDeathField;
            }
            set {
                this.reasonForDeathField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate1 {
            get {
                return this.sSDemographicsDate1Field;
            }
            set {
                this.sSDemographicsDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate1Specified {
            get {
                return this.sSDemographicsDate1FieldSpecified;
            }
            set {
                this.sSDemographicsDate1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate2 {
            get {
                return this.sSDemographicsDate2Field;
            }
            set {
                this.sSDemographicsDate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate2Specified {
            get {
                return this.sSDemographicsDate2FieldSpecified;
            }
            set {
                this.sSDemographicsDate2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate3 {
            get {
                return this.sSDemographicsDate3Field;
            }
            set {
                this.sSDemographicsDate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate3Specified {
            get {
                return this.sSDemographicsDate3FieldSpecified;
            }
            set {
                this.sSDemographicsDate3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate4 {
            get {
                return this.sSDemographicsDate4Field;
            }
            set {
                this.sSDemographicsDate4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate4Specified {
            get {
                return this.sSDemographicsDate4FieldSpecified;
            }
            set {
                this.sSDemographicsDate4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate5 {
            get {
                return this.sSDemographicsDate5Field;
            }
            set {
                this.sSDemographicsDate5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate5Specified {
            get {
                return this.sSDemographicsDate5FieldSpecified;
            }
            set {
                this.sSDemographicsDate5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict1 {
            get {
                return this.sSDemographicsDict1Field;
            }
            set {
                this.sSDemographicsDict1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict10 {
            get {
                return this.sSDemographicsDict10Field;
            }
            set {
                this.sSDemographicsDict10Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict2 {
            get {
                return this.sSDemographicsDict2Field;
            }
            set {
                this.sSDemographicsDict2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict3 {
            get {
                return this.sSDemographicsDict3Field;
            }
            set {
                this.sSDemographicsDict3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict4 {
            get {
                return this.sSDemographicsDict4Field;
            }
            set {
                this.sSDemographicsDict4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict5 {
            get {
                return this.sSDemographicsDict5Field;
            }
            set {
                this.sSDemographicsDict5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict6 {
            get {
                return this.sSDemographicsDict6Field;
            }
            set {
                this.sSDemographicsDict6Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict7 {
            get {
                return this.sSDemographicsDict7Field;
            }
            set {
                this.sSDemographicsDict7Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict8 {
            get {
                return this.sSDemographicsDict8Field;
            }
            set {
                this.sSDemographicsDict8Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict9 {
            get {
                return this.sSDemographicsDict9Field;
            }
            set {
                this.sSDemographicsDict9Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText201 {
            get {
                return this.sSDemographicsFreeText201Field;
            }
            set {
                this.sSDemographicsFreeText201Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText202 {
            get {
                return this.sSDemographicsFreeText202Field;
            }
            set {
                this.sSDemographicsFreeText202Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText203 {
            get {
                return this.sSDemographicsFreeText203Field;
            }
            set {
                this.sSDemographicsFreeText203Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText204 {
            get {
                return this.sSDemographicsFreeText204Field;
            }
            set {
                this.sSDemographicsFreeText204Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText205 {
            get {
                return this.sSDemographicsFreeText205Field;
            }
            set {
                this.sSDemographicsFreeText205Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText401 {
            get {
                return this.sSDemographicsFreeText401Field;
            }
            set {
                this.sSDemographicsFreeText401Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText402 {
            get {
                return this.sSDemographicsFreeText402Field;
            }
            set {
                this.sSDemographicsFreeText402Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText403 {
            get {
                return this.sSDemographicsFreeText403Field;
            }
            set {
                this.sSDemographicsFreeText403Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText404 {
            get {
                return this.sSDemographicsFreeText404Field;
            }
            set {
                this.sSDemographicsFreeText404Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText405 {
            get {
                return this.sSDemographicsFreeText405Field;
            }
            set {
                this.sSDemographicsFreeText405Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult1 {
            get {
                return this.sSDemographicsMult1Field;
            }
            set {
                this.sSDemographicsMult1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult2 {
            get {
                return this.sSDemographicsMult2Field;
            }
            set {
                this.sSDemographicsMult2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult3 {
            get {
                return this.sSDemographicsMult3Field;
            }
            set {
                this.sSDemographicsMult3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult4 {
            get {
                return this.sSDemographicsMult4Field;
            }
            set {
                this.sSDemographicsMult4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult5 {
            get {
                return this.sSDemographicsMult5Field;
            }
            set {
                this.sSDemographicsMult5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone1 {
            get {
                return this.sSDemographicsPhone1Field;
            }
            set {
                this.sSDemographicsPhone1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone2 {
            get {
                return this.sSDemographicsPhone2Field;
            }
            set {
                this.sSDemographicsPhone2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone3 {
            get {
                return this.sSDemographicsPhone3Field;
            }
            set {
                this.sSDemographicsPhone3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone4 {
            get {
                return this.sSDemographicsPhone4Field;
            }
            set {
                this.sSDemographicsPhone4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone5 {
            get {
                return this.sSDemographicsPhone5Field;
            }
            set {
                this.sSDemographicsPhone5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner1 {
            get {
                return this.sSDemographicsPractitioner1Field;
            }
            set {
                this.sSDemographicsPractitioner1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner2 {
            get {
                return this.sSDemographicsPractitioner2Field;
            }
            set {
                this.sSDemographicsPractitioner2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner3 {
            get {
                return this.sSDemographicsPractitioner3Field;
            }
            set {
                this.sSDemographicsPractitioner3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner4 {
            get {
                return this.sSDemographicsPractitioner4Field;
            }
            set {
                this.sSDemographicsPractitioner4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner5 {
            get {
                return this.sSDemographicsPractitioner5Field;
            }
            set {
                this.sSDemographicsPractitioner5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText1 {
            get {
                return this.sSDemographicsScrollFreeText1Field;
            }
            set {
                this.sSDemographicsScrollFreeText1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText2 {
            get {
                return this.sSDemographicsScrollFreeText2Field;
            }
            set {
                this.sSDemographicsScrollFreeText2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText3 {
            get {
                return this.sSDemographicsScrollFreeText3Field;
            }
            set {
                this.sSDemographicsScrollFreeText3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText4 {
            get {
                return this.sSDemographicsScrollFreeText4Field;
            }
            set {
                this.sSDemographicsScrollFreeText4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText5 {
            get {
                return this.sSDemographicsScrollFreeText5Field;
            }
            set {
                this.sSDemographicsScrollFreeText5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime1 {
            get {
                return this.sSDemographicsTime1Field;
            }
            set {
                this.sSDemographicsTime1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime2 {
            get {
                return this.sSDemographicsTime2Field;
            }
            set {
                this.sSDemographicsTime2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime3 {
            get {
                return this.sSDemographicsTime3Field;
            }
            set {
                this.sSDemographicsTime3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime4 {
            get {
                return this.sSDemographicsTime4Field;
            }
            set {
                this.sSDemographicsTime4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime5 {
            get {
                return this.sSDemographicsTime5Field;
            }
            set {
                this.sSDemographicsTime5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt20five {
            get {
                return this.sSDischAdmFreeTxt20fiveField;
            }
            set {
                this.sSDischAdmFreeTxt20fiveField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt20four {
            get {
                return this.sSDischAdmFreeTxt20fourField;
            }
            set {
                this.sSDischAdmFreeTxt20fourField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt20one {
            get {
                return this.sSDischAdmFreeTxt20oneField;
            }
            set {
                this.sSDischAdmFreeTxt20oneField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt20three {
            get {
                return this.sSDischAdmFreeTxt20threeField;
            }
            set {
                this.sSDischAdmFreeTxt20threeField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt20two {
            get {
                return this.sSDischAdmFreeTxt20twoField;
            }
            set {
                this.sSDischAdmFreeTxt20twoField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt40five {
            get {
                return this.sSDischAdmFreeTxt40fiveField;
            }
            set {
                this.sSDischAdmFreeTxt40fiveField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt40four {
            get {
                return this.sSDischAdmFreeTxt40fourField;
            }
            set {
                this.sSDischAdmFreeTxt40fourField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt40one {
            get {
                return this.sSDischAdmFreeTxt40oneField;
            }
            set {
                this.sSDischAdmFreeTxt40oneField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt40three {
            get {
                return this.sSDischAdmFreeTxt40threeField;
            }
            set {
                this.sSDischAdmFreeTxt40threeField = value;
            }
        }
        
        /// <remarks/>
        public string SSDischAdmFreeTxt40two {
            get {
                return this.sSDischAdmFreeTxt40twoField;
            }
            set {
                this.sSDischAdmFreeTxt40twoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDischargeAdmDate1 {
            get {
                return this.sSDischargeAdmDate1Field;
            }
            set {
                this.sSDischargeAdmDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDischargeAdmDate1Specified {
            get {
                return this.sSDischargeAdmDate1FieldSpecified;
            }
            set {
                this.sSDischargeAdmDate1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDischargeAdmDate2 {
            get {
                return this.sSDischargeAdmDate2Field;
            }
            set {
                this.sSDischargeAdmDate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDischargeAdmDate2Specified {
            get {
                return this.sSDischargeAdmDate2FieldSpecified;
            }
            set {
                this.sSDischargeAdmDate2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDischargeAdmDate3 {
            get {
                return this.sSDischargeAdmDate3Field;
            }
            set {
                this.sSDischargeAdmDate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDischargeAdmDate3Specified {
            get {
                return this.sSDischargeAdmDate3FieldSpecified;
            }
            set {
                this.sSDischargeAdmDate3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDischargeAdmDate4 {
            get {
                return this.sSDischargeAdmDate4Field;
            }
            set {
                this.sSDischargeAdmDate4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDischargeAdmDate4Specified {
            get {
                return this.sSDischargeAdmDate4FieldSpecified;
            }
            set {
                this.sSDischargeAdmDate4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDischargeAdmDate5 {
            get {
                return this.sSDischargeAdmDate5Field;
            }
            set {
                this.sSDischargeAdmDate5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDischargeAdmDate5Specified {
            get {
                return this.sSDischargeAdmDate5FieldSpecified;
            }
            set {
                this.sSDischargeAdmDate5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict1 {
            get {
                return this.sSDischargeAdmDict1Field;
            }
            set {
                this.sSDischargeAdmDict1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict2 {
            get {
                return this.sSDischargeAdmDict2Field;
            }
            set {
                this.sSDischargeAdmDict2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict3 {
            get {
                return this.sSDischargeAdmDict3Field;
            }
            set {
                this.sSDischargeAdmDict3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict4 {
            get {
                return this.sSDischargeAdmDict4Field;
            }
            set {
                this.sSDischargeAdmDict4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict5 {
            get {
                return this.sSDischargeAdmDict5Field;
            }
            set {
                this.sSDischargeAdmDict5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict6 {
            get {
                return this.sSDischargeAdmDict6Field;
            }
            set {
                this.sSDischargeAdmDict6Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict7 {
            get {
                return this.sSDischargeAdmDict7Field;
            }
            set {
                this.sSDischargeAdmDict7Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict8 {
            get {
                return this.sSDischargeAdmDict8Field;
            }
            set {
                this.sSDischargeAdmDict8Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmDict9 {
            get {
                return this.sSDischargeAdmDict9Field;
            }
            set {
                this.sSDischargeAdmDict9Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmFreeTxt1 {
            get {
                return this.sSDischargeAdmFreeTxt1Field;
            }
            set {
                this.sSDischargeAdmFreeTxt1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmFreeTxt2 {
            get {
                return this.sSDischargeAdmFreeTxt2Field;
            }
            set {
                this.sSDischargeAdmFreeTxt2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmFreeTxt3 {
            get {
                return this.sSDischargeAdmFreeTxt3Field;
            }
            set {
                this.sSDischargeAdmFreeTxt3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmFreeTxt4 {
            get {
                return this.sSDischargeAdmFreeTxt4Field;
            }
            set {
                this.sSDischargeAdmFreeTxt4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmFreeTxt5 {
            get {
                return this.sSDischargeAdmFreeTxt5Field;
            }
            set {
                this.sSDischargeAdmFreeTxt5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmMult1 {
            get {
                return this.sSDischargeAdmMult1Field;
            }
            set {
                this.sSDischargeAdmMult1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmMult2 {
            get {
                return this.sSDischargeAdmMult2Field;
            }
            set {
                this.sSDischargeAdmMult2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmStaff1 {
            get {
                return this.sSDischargeAdmStaff1Field;
            }
            set {
                this.sSDischargeAdmStaff1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmStaff2 {
            get {
                return this.sSDischargeAdmStaff2Field;
            }
            set {
                this.sSDischargeAdmStaff2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmStaff3 {
            get {
                return this.sSDischargeAdmStaff3Field;
            }
            set {
                this.sSDischargeAdmStaff3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmStaff4 {
            get {
                return this.sSDischargeAdmStaff4Field;
            }
            set {
                this.sSDischargeAdmStaff4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmStaff5 {
            get {
                return this.sSDischargeAdmStaff5Field;
            }
            set {
                this.sSDischargeAdmStaff5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmTime1 {
            get {
                return this.sSDischargeAdmTime1Field;
            }
            set {
                this.sSDischargeAdmTime1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmTime2 {
            get {
                return this.sSDischargeAdmTime2Field;
            }
            set {
                this.sSDischargeAdmTime2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmTime3 {
            get {
                return this.sSDischargeAdmTime3Field;
            }
            set {
                this.sSDischargeAdmTime3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmTime4 {
            get {
                return this.sSDischargeAdmTime4Field;
            }
            set {
                this.sSDischargeAdmTime4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDischargeAdmTime5 {
            get {
                return this.sSDischargeAdmTime5Field;
            }
            set {
                this.sSDischargeAdmTime5Field = value;
            }
        }
        
        /// <remarks/>
        public string SecPresentingProblem {
            get {
                return this.secPresentingProblemField;
            }
            set {
                this.secPresentingProblemField = value;
            }
        }
        
        /// <remarks/>
        public string TertPresentingProblem {
            get {
                return this.tertPresentingProblemField;
            }
            set {
                this.tertPresentingProblemField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfDischarge {
            get {
                return this.typeOfDischargeField;
            }
            set {
                this.typeOfDischargeField = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber1 {
            get {
                return this.policyNumber1Field;
            }
            set {
                this.policyNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor1 {
            get {
                return this.guarantor1Field;
            }
            set {
                this.guarantor1Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber2 {
            get {
                return this.policyNumber2Field;
            }
            set {
                this.policyNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor2 {
            get {
                return this.guarantor2Field;
            }
            set {
                this.guarantor2Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber3 {
            get {
                return this.policyNumber3Field;
            }
            set {
                this.policyNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor3 {
            get {
                return this.guarantor3Field;
            }
            set {
                this.guarantor3Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber4 {
            get {
                return this.policyNumber4Field;
            }
            set {
                this.policyNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor4 {
            get {
                return this.guarantor4Field;
            }
            set {
                this.guarantor4Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber5 {
            get {
                return this.policyNumber5Field;
            }
            set {
                this.policyNumber5Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor5 {
            get {
                return this.guarantor5Field;
            }
            set {
                this.guarantor5Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber6 {
            get {
                return this.policyNumber6Field;
            }
            set {
                this.policyNumber6Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor6 {
            get {
                return this.guarantor6Field;
            }
            set {
                this.guarantor6Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber7 {
            get {
                return this.policyNumber7Field;
            }
            set {
                this.policyNumber7Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor7 {
            get {
                return this.guarantor7Field;
            }
            set {
                this.guarantor7Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber8 {
            get {
                return this.policyNumber8Field;
            }
            set {
                this.policyNumber8Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor8 {
            get {
                return this.guarantor8Field;
            }
            set {
                this.guarantor8Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber9 {
            get {
                return this.policyNumber9Field;
            }
            set {
                this.policyNumber9Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor9 {
            get {
                return this.guarantor9Field;
            }
            set {
                this.guarantor9Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber10 {
            get {
                return this.policyNumber10Field;
            }
            set {
                this.policyNumber10Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor10 {
            get {
                return this.guarantor10Field;
            }
            set {
                this.guarantor10Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DischargeClientCompletedEventHandler(object sender, DischargeClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DischargeClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DischargeClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591