'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ClientChargeWS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientChargeInputObject", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClientChargeInputObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentConfirmedField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentEndTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentNotesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentSiteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentStartTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BillableField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CoPractitionerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfirmationNotesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CostOfServiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOfServiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DurationField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EpisodeNumberField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GroupNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MedicalDiagnosis1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MedicalDiagnosis2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MissedVisitField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MissedVisitNotesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MissedVisitServiceCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiersField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoteReferenceCode837BillingField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoteReferenceText837BillingField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberOfClientsField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OralCavityDesignationCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PractitionerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriorPlacementDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProgramField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProsthesisCrownOrInlayCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferringPractitionerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferringProviderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTxMultipleSelectDictionary1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDSMCode1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDSMCode2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDSMCode3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDSMCode4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDSMCode5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDate1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDate2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDate3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDate4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDate5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary6Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary7Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary8Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentDictionary9Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText101Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText102Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText103Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText104Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText105Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText401Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText402Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText403Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText404Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText405Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText801Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText802Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText803Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText804Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentFreeText805Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentGuarantor1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentGuarantor2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentGuarantor3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentGuarantor4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentGuarantor5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentICD9Code1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentICD9Code2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentICD9Code3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentICD9Code4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentICD9Code5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentPractitioner1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentPractitioner2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentPractitioner3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentPractitioner4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentPractitioner5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentScrollingFreeText1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentScrollingFreeText2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentScrollingFreeText3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentScrollingFreeText4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTreatmentScrollingFreeText5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSTxMultipleSelectDictionary2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecondCoStaffMemberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceEndTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceStartTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToothNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToothStatusCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToothSurfaceCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitsOfServiceField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MedicalDiagnosis3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MedicalDiagnosis4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisciplineField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InitialTxDate2300DTP03Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOfAccident2300DTP03Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormLoc10AutoAccidentPlaceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RelatedCausesInfo2300CLM11Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstBillingDateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentConfirmed() As String
            Get
                Return Me.AppointmentConfirmedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentConfirmedField, value) <> true) Then
                    Me.AppointmentConfirmedField = value
                    Me.RaisePropertyChanged("AppointmentConfirmed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentDate() As String
            Get
                Return Me.AppointmentDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentDateField, value) <> true) Then
                    Me.AppointmentDateField = value
                    Me.RaisePropertyChanged("AppointmentDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentEndTime() As String
            Get
                Return Me.AppointmentEndTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentEndTimeField, value) <> true) Then
                    Me.AppointmentEndTimeField = value
                    Me.RaisePropertyChanged("AppointmentEndTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentNotes() As String
            Get
                Return Me.AppointmentNotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentNotesField, value) <> true) Then
                    Me.AppointmentNotesField = value
                    Me.RaisePropertyChanged("AppointmentNotes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentSite() As String
            Get
                Return Me.AppointmentSiteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentSiteField, value) <> true) Then
                    Me.AppointmentSiteField = value
                    Me.RaisePropertyChanged("AppointmentSite")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentStartTime() As String
            Get
                Return Me.AppointmentStartTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentStartTimeField, value) <> true) Then
                    Me.AppointmentStartTimeField = value
                    Me.RaisePropertyChanged("AppointmentStartTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AppointmentStatus() As String
            Get
                Return Me.AppointmentStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppointmentStatusField, value) <> true) Then
                    Me.AppointmentStatusField = value
                    Me.RaisePropertyChanged("AppointmentStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Billable() As String
            Get
                Return Me.BillableField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BillableField, value) <> true) Then
                    Me.BillableField = value
                    Me.RaisePropertyChanged("Billable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientID() As String
            Get
                Return Me.ClientIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientIDField, value) <> true) Then
                    Me.ClientIDField = value
                    Me.RaisePropertyChanged("ClientID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CoPractitioner() As String
            Get
                Return Me.CoPractitionerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CoPractitionerField, value) <> true) Then
                    Me.CoPractitionerField = value
                    Me.RaisePropertyChanged("CoPractitioner")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ConfirmationNotes() As String
            Get
                Return Me.ConfirmationNotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConfirmationNotesField, value) <> true) Then
                    Me.ConfirmationNotesField = value
                    Me.RaisePropertyChanged("ConfirmationNotes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CostOfService() As String
            Get
                Return Me.CostOfServiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CostOfServiceField, value) <> true) Then
                    Me.CostOfServiceField = value
                    Me.RaisePropertyChanged("CostOfService")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DateOfService() As String
            Get
                Return Me.DateOfServiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateOfServiceField, value) <> true) Then
                    Me.DateOfServiceField = value
                    Me.RaisePropertyChanged("DateOfService")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Duration() As Long
            Get
                Return Me.DurationField
            End Get
            Set
                If (Me.DurationField.Equals(value) <> true) Then
                    Me.DurationField = value
                    Me.RaisePropertyChanged("Duration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EpisodeNumber() As Long
            Get
                Return Me.EpisodeNumberField
            End Get
            Set
                If (Me.EpisodeNumberField.Equals(value) <> true) Then
                    Me.EpisodeNumberField = value
                    Me.RaisePropertyChanged("EpisodeNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GroupNumber() As String
            Get
                Return Me.GroupNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GroupNumberField, value) <> true) Then
                    Me.GroupNumberField = value
                    Me.RaisePropertyChanged("GroupNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MedicalDiagnosis1() As String
            Get
                Return Me.MedicalDiagnosis1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MedicalDiagnosis1Field, value) <> true) Then
                    Me.MedicalDiagnosis1Field = value
                    Me.RaisePropertyChanged("MedicalDiagnosis1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MedicalDiagnosis2() As String
            Get
                Return Me.MedicalDiagnosis2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MedicalDiagnosis2Field, value) <> true) Then
                    Me.MedicalDiagnosis2Field = value
                    Me.RaisePropertyChanged("MedicalDiagnosis2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MissedVisit() As String
            Get
                Return Me.MissedVisitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MissedVisitField, value) <> true) Then
                    Me.MissedVisitField = value
                    Me.RaisePropertyChanged("MissedVisit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MissedVisitNotes() As String
            Get
                Return Me.MissedVisitNotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MissedVisitNotesField, value) <> true) Then
                    Me.MissedVisitNotesField = value
                    Me.RaisePropertyChanged("MissedVisitNotes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MissedVisitServiceCode() As String
            Get
                Return Me.MissedVisitServiceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MissedVisitServiceCodeField, value) <> true) Then
                    Me.MissedVisitServiceCodeField = value
                    Me.RaisePropertyChanged("MissedVisitServiceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Modifiers() As String
            Get
                Return Me.ModifiersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModifiersField, value) <> true) Then
                    Me.ModifiersField = value
                    Me.RaisePropertyChanged("Modifiers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NoteReferenceCode837Billing() As String
            Get
                Return Me.NoteReferenceCode837BillingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoteReferenceCode837BillingField, value) <> true) Then
                    Me.NoteReferenceCode837BillingField = value
                    Me.RaisePropertyChanged("NoteReferenceCode837Billing")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NoteReferenceText837Billing() As String
            Get
                Return Me.NoteReferenceText837BillingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NoteReferenceText837BillingField, value) <> true) Then
                    Me.NoteReferenceText837BillingField = value
                    Me.RaisePropertyChanged("NoteReferenceText837Billing")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumberOfClients() As Long
            Get
                Return Me.NumberOfClientsField
            End Get
            Set
                If (Me.NumberOfClientsField.Equals(value) <> true) Then
                    Me.NumberOfClientsField = value
                    Me.RaisePropertyChanged("NumberOfClients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OralCavityDesignationCode() As String
            Get
                Return Me.OralCavityDesignationCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OralCavityDesignationCodeField, value) <> true) Then
                    Me.OralCavityDesignationCodeField = value
                    Me.RaisePropertyChanged("OralCavityDesignationCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Practitioner() As String
            Get
                Return Me.PractitionerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PractitionerField, value) <> true) Then
                    Me.PractitionerField = value
                    Me.RaisePropertyChanged("Practitioner")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PriorPlacementDate() As String
            Get
                Return Me.PriorPlacementDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PriorPlacementDateField, value) <> true) Then
                    Me.PriorPlacementDateField = value
                    Me.RaisePropertyChanged("PriorPlacementDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Program() As String
            Get
                Return Me.ProgramField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProgramField, value) <> true) Then
                    Me.ProgramField = value
                    Me.RaisePropertyChanged("Program")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ProsthesisCrownOrInlayCode() As String
            Get
                Return Me.ProsthesisCrownOrInlayCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProsthesisCrownOrInlayCodeField, value) <> true) Then
                    Me.ProsthesisCrownOrInlayCodeField = value
                    Me.RaisePropertyChanged("ProsthesisCrownOrInlayCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ReferringPractitioner() As String
            Get
                Return Me.ReferringPractitionerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferringPractitionerField, value) <> true) Then
                    Me.ReferringPractitionerField = value
                    Me.RaisePropertyChanged("ReferringPractitioner")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ReferringProvider() As String
            Get
                Return Me.ReferringProviderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferringProviderField, value) <> true) Then
                    Me.ReferringProviderField = value
                    Me.RaisePropertyChanged("ReferringProvider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSTxMultipleSelectDictionary1() As String
            Get
                Return Me.SSTxMultipleSelectDictionary1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTxMultipleSelectDictionary1Field, value) <> true) Then
                    Me.SSTxMultipleSelectDictionary1Field = value
                    Me.RaisePropertyChanged("SSTxMultipleSelectDictionary1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=34)>  _
        Public Property SSTreatmentDSMCode1() As String
            Get
                Return Me.SSTreatmentDSMCode1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDSMCode1Field, value) <> true) Then
                    Me.SSTreatmentDSMCode1Field = value
                    Me.RaisePropertyChanged("SSTreatmentDSMCode1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=35)>  _
        Public Property SSTreatmentDSMCode2() As String
            Get
                Return Me.SSTreatmentDSMCode2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDSMCode2Field, value) <> true) Then
                    Me.SSTreatmentDSMCode2Field = value
                    Me.RaisePropertyChanged("SSTreatmentDSMCode2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=36)>  _
        Public Property SSTreatmentDSMCode3() As String
            Get
                Return Me.SSTreatmentDSMCode3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDSMCode3Field, value) <> true) Then
                    Me.SSTreatmentDSMCode3Field = value
                    Me.RaisePropertyChanged("SSTreatmentDSMCode3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=37)>  _
        Public Property SSTreatmentDSMCode4() As String
            Get
                Return Me.SSTreatmentDSMCode4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDSMCode4Field, value) <> true) Then
                    Me.SSTreatmentDSMCode4Field = value
                    Me.RaisePropertyChanged("SSTreatmentDSMCode4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=38)>  _
        Public Property SSTreatmentDSMCode5() As String
            Get
                Return Me.SSTreatmentDSMCode5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDSMCode5Field, value) <> true) Then
                    Me.SSTreatmentDSMCode5Field = value
                    Me.RaisePropertyChanged("SSTreatmentDSMCode5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=39)>  _
        Public Property SSTreatmentDate1() As String
            Get
                Return Me.SSTreatmentDate1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDate1Field, value) <> true) Then
                    Me.SSTreatmentDate1Field = value
                    Me.RaisePropertyChanged("SSTreatmentDate1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=40)>  _
        Public Property SSTreatmentDate2() As String
            Get
                Return Me.SSTreatmentDate2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDate2Field, value) <> true) Then
                    Me.SSTreatmentDate2Field = value
                    Me.RaisePropertyChanged("SSTreatmentDate2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=41)>  _
        Public Property SSTreatmentDate3() As String
            Get
                Return Me.SSTreatmentDate3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDate3Field, value) <> true) Then
                    Me.SSTreatmentDate3Field = value
                    Me.RaisePropertyChanged("SSTreatmentDate3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=42)>  _
        Public Property SSTreatmentDate4() As String
            Get
                Return Me.SSTreatmentDate4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDate4Field, value) <> true) Then
                    Me.SSTreatmentDate4Field = value
                    Me.RaisePropertyChanged("SSTreatmentDate4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=43)>  _
        Public Property SSTreatmentDate5() As String
            Get
                Return Me.SSTreatmentDate5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDate5Field, value) <> true) Then
                    Me.SSTreatmentDate5Field = value
                    Me.RaisePropertyChanged("SSTreatmentDate5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=44)>  _
        Public Property SSTreatmentDictionary1() As String
            Get
                Return Me.SSTreatmentDictionary1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary1Field, value) <> true) Then
                    Me.SSTreatmentDictionary1Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=45)>  _
        Public Property SSTreatmentDictionary2() As String
            Get
                Return Me.SSTreatmentDictionary2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary2Field, value) <> true) Then
                    Me.SSTreatmentDictionary2Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=46)>  _
        Public Property SSTreatmentDictionary3() As String
            Get
                Return Me.SSTreatmentDictionary3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary3Field, value) <> true) Then
                    Me.SSTreatmentDictionary3Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=47)>  _
        Public Property SSTreatmentDictionary4() As String
            Get
                Return Me.SSTreatmentDictionary4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary4Field, value) <> true) Then
                    Me.SSTreatmentDictionary4Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=48)>  _
        Public Property SSTreatmentDictionary5() As String
            Get
                Return Me.SSTreatmentDictionary5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary5Field, value) <> true) Then
                    Me.SSTreatmentDictionary5Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=49)>  _
        Public Property SSTreatmentDictionary6() As String
            Get
                Return Me.SSTreatmentDictionary6Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary6Field, value) <> true) Then
                    Me.SSTreatmentDictionary6Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=50)>  _
        Public Property SSTreatmentDictionary7() As String
            Get
                Return Me.SSTreatmentDictionary7Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary7Field, value) <> true) Then
                    Me.SSTreatmentDictionary7Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=51)>  _
        Public Property SSTreatmentDictionary8() As String
            Get
                Return Me.SSTreatmentDictionary8Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary8Field, value) <> true) Then
                    Me.SSTreatmentDictionary8Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=52)>  _
        Public Property SSTreatmentDictionary9() As String
            Get
                Return Me.SSTreatmentDictionary9Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentDictionary9Field, value) <> true) Then
                    Me.SSTreatmentDictionary9Field = value
                    Me.RaisePropertyChanged("SSTreatmentDictionary9")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=53)>  _
        Public Property SSTreatmentFreeText101() As String
            Get
                Return Me.SSTreatmentFreeText101Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText101Field, value) <> true) Then
                    Me.SSTreatmentFreeText101Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText101")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=54)>  _
        Public Property SSTreatmentFreeText102() As String
            Get
                Return Me.SSTreatmentFreeText102Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText102Field, value) <> true) Then
                    Me.SSTreatmentFreeText102Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText102")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=55)>  _
        Public Property SSTreatmentFreeText103() As String
            Get
                Return Me.SSTreatmentFreeText103Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText103Field, value) <> true) Then
                    Me.SSTreatmentFreeText103Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText103")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=56)>  _
        Public Property SSTreatmentFreeText104() As String
            Get
                Return Me.SSTreatmentFreeText104Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText104Field, value) <> true) Then
                    Me.SSTreatmentFreeText104Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText104")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=57)>  _
        Public Property SSTreatmentFreeText105() As String
            Get
                Return Me.SSTreatmentFreeText105Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText105Field, value) <> true) Then
                    Me.SSTreatmentFreeText105Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText105")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=58)>  _
        Public Property SSTreatmentFreeText401() As String
            Get
                Return Me.SSTreatmentFreeText401Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText401Field, value) <> true) Then
                    Me.SSTreatmentFreeText401Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText401")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=59)>  _
        Public Property SSTreatmentFreeText402() As String
            Get
                Return Me.SSTreatmentFreeText402Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText402Field, value) <> true) Then
                    Me.SSTreatmentFreeText402Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText402")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=60)>  _
        Public Property SSTreatmentFreeText403() As String
            Get
                Return Me.SSTreatmentFreeText403Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText403Field, value) <> true) Then
                    Me.SSTreatmentFreeText403Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText403")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=61)>  _
        Public Property SSTreatmentFreeText404() As String
            Get
                Return Me.SSTreatmentFreeText404Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText404Field, value) <> true) Then
                    Me.SSTreatmentFreeText404Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText404")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=62)>  _
        Public Property SSTreatmentFreeText405() As String
            Get
                Return Me.SSTreatmentFreeText405Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText405Field, value) <> true) Then
                    Me.SSTreatmentFreeText405Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText405")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=63)>  _
        Public Property SSTreatmentFreeText801() As String
            Get
                Return Me.SSTreatmentFreeText801Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText801Field, value) <> true) Then
                    Me.SSTreatmentFreeText801Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText801")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=64)>  _
        Public Property SSTreatmentFreeText802() As String
            Get
                Return Me.SSTreatmentFreeText802Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText802Field, value) <> true) Then
                    Me.SSTreatmentFreeText802Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText802")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=65)>  _
        Public Property SSTreatmentFreeText803() As String
            Get
                Return Me.SSTreatmentFreeText803Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText803Field, value) <> true) Then
                    Me.SSTreatmentFreeText803Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText803")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=66)>  _
        Public Property SSTreatmentFreeText804() As String
            Get
                Return Me.SSTreatmentFreeText804Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText804Field, value) <> true) Then
                    Me.SSTreatmentFreeText804Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText804")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=67)>  _
        Public Property SSTreatmentFreeText805() As String
            Get
                Return Me.SSTreatmentFreeText805Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentFreeText805Field, value) <> true) Then
                    Me.SSTreatmentFreeText805Field = value
                    Me.RaisePropertyChanged("SSTreatmentFreeText805")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=68)>  _
        Public Property SSTreatmentGuarantor1() As String
            Get
                Return Me.SSTreatmentGuarantor1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentGuarantor1Field, value) <> true) Then
                    Me.SSTreatmentGuarantor1Field = value
                    Me.RaisePropertyChanged("SSTreatmentGuarantor1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=69)>  _
        Public Property SSTreatmentGuarantor2() As String
            Get
                Return Me.SSTreatmentGuarantor2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentGuarantor2Field, value) <> true) Then
                    Me.SSTreatmentGuarantor2Field = value
                    Me.RaisePropertyChanged("SSTreatmentGuarantor2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=70)>  _
        Public Property SSTreatmentGuarantor3() As String
            Get
                Return Me.SSTreatmentGuarantor3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentGuarantor3Field, value) <> true) Then
                    Me.SSTreatmentGuarantor3Field = value
                    Me.RaisePropertyChanged("SSTreatmentGuarantor3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=71)>  _
        Public Property SSTreatmentGuarantor4() As String
            Get
                Return Me.SSTreatmentGuarantor4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentGuarantor4Field, value) <> true) Then
                    Me.SSTreatmentGuarantor4Field = value
                    Me.RaisePropertyChanged("SSTreatmentGuarantor4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=72)>  _
        Public Property SSTreatmentGuarantor5() As String
            Get
                Return Me.SSTreatmentGuarantor5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentGuarantor5Field, value) <> true) Then
                    Me.SSTreatmentGuarantor5Field = value
                    Me.RaisePropertyChanged("SSTreatmentGuarantor5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=73)>  _
        Public Property SSTreatmentICD9Code1() As String
            Get
                Return Me.SSTreatmentICD9Code1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentICD9Code1Field, value) <> true) Then
                    Me.SSTreatmentICD9Code1Field = value
                    Me.RaisePropertyChanged("SSTreatmentICD9Code1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=74)>  _
        Public Property SSTreatmentICD9Code2() As String
            Get
                Return Me.SSTreatmentICD9Code2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentICD9Code2Field, value) <> true) Then
                    Me.SSTreatmentICD9Code2Field = value
                    Me.RaisePropertyChanged("SSTreatmentICD9Code2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=75)>  _
        Public Property SSTreatmentICD9Code3() As String
            Get
                Return Me.SSTreatmentICD9Code3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentICD9Code3Field, value) <> true) Then
                    Me.SSTreatmentICD9Code3Field = value
                    Me.RaisePropertyChanged("SSTreatmentICD9Code3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=76)>  _
        Public Property SSTreatmentICD9Code4() As String
            Get
                Return Me.SSTreatmentICD9Code4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentICD9Code4Field, value) <> true) Then
                    Me.SSTreatmentICD9Code4Field = value
                    Me.RaisePropertyChanged("SSTreatmentICD9Code4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=77)>  _
        Public Property SSTreatmentICD9Code5() As String
            Get
                Return Me.SSTreatmentICD9Code5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentICD9Code5Field, value) <> true) Then
                    Me.SSTreatmentICD9Code5Field = value
                    Me.RaisePropertyChanged("SSTreatmentICD9Code5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=78)>  _
        Public Property SSTreatmentPractitioner1() As String
            Get
                Return Me.SSTreatmentPractitioner1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentPractitioner1Field, value) <> true) Then
                    Me.SSTreatmentPractitioner1Field = value
                    Me.RaisePropertyChanged("SSTreatmentPractitioner1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=79)>  _
        Public Property SSTreatmentPractitioner2() As String
            Get
                Return Me.SSTreatmentPractitioner2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentPractitioner2Field, value) <> true) Then
                    Me.SSTreatmentPractitioner2Field = value
                    Me.RaisePropertyChanged("SSTreatmentPractitioner2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=80)>  _
        Public Property SSTreatmentPractitioner3() As String
            Get
                Return Me.SSTreatmentPractitioner3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentPractitioner3Field, value) <> true) Then
                    Me.SSTreatmentPractitioner3Field = value
                    Me.RaisePropertyChanged("SSTreatmentPractitioner3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=81)>  _
        Public Property SSTreatmentPractitioner4() As String
            Get
                Return Me.SSTreatmentPractitioner4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentPractitioner4Field, value) <> true) Then
                    Me.SSTreatmentPractitioner4Field = value
                    Me.RaisePropertyChanged("SSTreatmentPractitioner4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=82)>  _
        Public Property SSTreatmentPractitioner5() As String
            Get
                Return Me.SSTreatmentPractitioner5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentPractitioner5Field, value) <> true) Then
                    Me.SSTreatmentPractitioner5Field = value
                    Me.RaisePropertyChanged("SSTreatmentPractitioner5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=83)>  _
        Public Property SSTreatmentScrollingFreeText1() As String
            Get
                Return Me.SSTreatmentScrollingFreeText1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentScrollingFreeText1Field, value) <> true) Then
                    Me.SSTreatmentScrollingFreeText1Field = value
                    Me.RaisePropertyChanged("SSTreatmentScrollingFreeText1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=84)>  _
        Public Property SSTreatmentScrollingFreeText2() As String
            Get
                Return Me.SSTreatmentScrollingFreeText2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentScrollingFreeText2Field, value) <> true) Then
                    Me.SSTreatmentScrollingFreeText2Field = value
                    Me.RaisePropertyChanged("SSTreatmentScrollingFreeText2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=85)>  _
        Public Property SSTreatmentScrollingFreeText3() As String
            Get
                Return Me.SSTreatmentScrollingFreeText3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentScrollingFreeText3Field, value) <> true) Then
                    Me.SSTreatmentScrollingFreeText3Field = value
                    Me.RaisePropertyChanged("SSTreatmentScrollingFreeText3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=86)>  _
        Public Property SSTreatmentScrollingFreeText4() As String
            Get
                Return Me.SSTreatmentScrollingFreeText4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentScrollingFreeText4Field, value) <> true) Then
                    Me.SSTreatmentScrollingFreeText4Field = value
                    Me.RaisePropertyChanged("SSTreatmentScrollingFreeText4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=87)>  _
        Public Property SSTreatmentScrollingFreeText5() As String
            Get
                Return Me.SSTreatmentScrollingFreeText5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTreatmentScrollingFreeText5Field, value) <> true) Then
                    Me.SSTreatmentScrollingFreeText5Field = value
                    Me.RaisePropertyChanged("SSTreatmentScrollingFreeText5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=88)>  _
        Public Property SSTxMultipleSelectDictionary2() As String
            Get
                Return Me.SSTxMultipleSelectDictionary2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSTxMultipleSelectDictionary2Field, value) <> true) Then
                    Me.SSTxMultipleSelectDictionary2Field = value
                    Me.RaisePropertyChanged("SSTxMultipleSelectDictionary2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=89)>  _
        Public Property SecondCoStaffMember() As String
            Get
                Return Me.SecondCoStaffMemberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecondCoStaffMemberField, value) <> true) Then
                    Me.SecondCoStaffMemberField = value
                    Me.RaisePropertyChanged("SecondCoStaffMember")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=90)>  _
        Public Property ServiceCode() As String
            Get
                Return Me.ServiceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceCodeField, value) <> true) Then
                    Me.ServiceCodeField = value
                    Me.RaisePropertyChanged("ServiceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=91)>  _
        Public Property ServiceEndTime() As String
            Get
                Return Me.ServiceEndTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceEndTimeField, value) <> true) Then
                    Me.ServiceEndTimeField = value
                    Me.RaisePropertyChanged("ServiceEndTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=92)>  _
        Public Property ServiceStartTime() As String
            Get
                Return Me.ServiceStartTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceStartTimeField, value) <> true) Then
                    Me.ServiceStartTimeField = value
                    Me.RaisePropertyChanged("ServiceStartTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=93)>  _
        Public Property ToothNumber() As String
            Get
                Return Me.ToothNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToothNumberField, value) <> true) Then
                    Me.ToothNumberField = value
                    Me.RaisePropertyChanged("ToothNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=94)>  _
        Public Property ToothStatusCode() As String
            Get
                Return Me.ToothStatusCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToothStatusCodeField, value) <> true) Then
                    Me.ToothStatusCodeField = value
                    Me.RaisePropertyChanged("ToothStatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=95)>  _
        Public Property ToothSurfaceCode() As String
            Get
                Return Me.ToothSurfaceCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToothSurfaceCodeField, value) <> true) Then
                    Me.ToothSurfaceCodeField = value
                    Me.RaisePropertyChanged("ToothSurfaceCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=96)>  _
        Public Property UnitsOfService() As Decimal
            Get
                Return Me.UnitsOfServiceField
            End Get
            Set
                If (Me.UnitsOfServiceField.Equals(value) <> true) Then
                    Me.UnitsOfServiceField = value
                    Me.RaisePropertyChanged("UnitsOfService")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=97)>  _
        Public Property MedicalDiagnosis3() As String
            Get
                Return Me.MedicalDiagnosis3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MedicalDiagnosis3Field, value) <> true) Then
                    Me.MedicalDiagnosis3Field = value
                    Me.RaisePropertyChanged("MedicalDiagnosis3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=98)>  _
        Public Property MedicalDiagnosis4() As String
            Get
                Return Me.MedicalDiagnosis4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MedicalDiagnosis4Field, value) <> true) Then
                    Me.MedicalDiagnosis4Field = value
                    Me.RaisePropertyChanged("MedicalDiagnosis4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=99)>  _
        Public Property Discipline() As String
            Get
                Return Me.DisciplineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisciplineField, value) <> true) Then
                    Me.DisciplineField = value
                    Me.RaisePropertyChanged("Discipline")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=100)>  _
        Public Property ServiceStatus() As String
            Get
                Return Me.ServiceStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceStatusField, value) <> true) Then
                    Me.ServiceStatusField = value
                    Me.RaisePropertyChanged("ServiceStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=101)>  _
        Public Property InitialTxDate2300DTP03() As String
            Get
                Return Me.InitialTxDate2300DTP03Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.InitialTxDate2300DTP03Field, value) <> true) Then
                    Me.InitialTxDate2300DTP03Field = value
                    Me.RaisePropertyChanged("InitialTxDate2300DTP03")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=102)>  _
        Public Property DateOfAccident2300DTP03() As String
            Get
                Return Me.DateOfAccident2300DTP03Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateOfAccident2300DTP03Field, value) <> true) Then
                    Me.DateOfAccident2300DTP03Field = value
                    Me.RaisePropertyChanged("DateOfAccident2300DTP03")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=103)>  _
        Public Property FormLoc10AutoAccidentPlace() As String
            Get
                Return Me.FormLoc10AutoAccidentPlaceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormLoc10AutoAccidentPlaceField, value) <> true) Then
                    Me.FormLoc10AutoAccidentPlaceField = value
                    Me.RaisePropertyChanged("FormLoc10AutoAccidentPlace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=104)>  _
        Public Property RelatedCausesInfo2300CLM11() As String
            Get
                Return Me.RelatedCausesInfo2300CLM11Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.RelatedCausesInfo2300CLM11Field, value) <> true) Then
                    Me.RelatedCausesInfo2300CLM11Field = value
                    Me.RaisePropertyChanged("RelatedCausesInfo2300CLM11")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=105)>  _
        Public Property FirstBillingDate() As String
            Get
                Return Me.FirstBillingDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstBillingDateField, value) <> true) Then
                    Me.FirstBillingDateField = value
                    Me.RaisePropertyChanged("FirstBillingDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WebServiceResponse", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WebServiceResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfirmationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Confirmation() As String
            Get
                Return Me.ConfirmationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConfirmationField, value) <> true) Then
                    Me.ConfirmationField = value
                    Me.RaisePropertyChanged("Confirmation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As Boolean
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfDictionaryItemObjectDictionaryItemObject", [Namespace]:="http://tempuri.org", ItemName:="DictionaryItemObject"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfDictionaryItemObjectDictionaryItemObject
        Inherits System.Collections.Generic.List(Of ClientChargeWS.DictionaryItemObject)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DictionaryItemObject", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DictionaryItemObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryFieldDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryUniqueIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MesgField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryCode() As String
            Get
                Return Me.DictionaryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryCodeField, value) <> true) Then
                    Me.DictionaryCodeField = value
                    Me.RaisePropertyChanged("DictionaryCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryFieldDescription() As String
            Get
                Return Me.DictionaryFieldDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryFieldDescriptionField, value) <> true) Then
                    Me.DictionaryFieldDescriptionField = value
                    Me.RaisePropertyChanged("DictionaryFieldDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryUniqueId() As String
            Get
                Return Me.DictionaryUniqueIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryUniqueIdField, value) <> true) Then
                    Me.DictionaryUniqueIdField = value
                    Me.RaisePropertyChanged("DictionaryUniqueId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryValue() As String
            Get
                Return Me.DictionaryValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryValueField, value) <> true) Then
                    Me.DictionaryValueField = value
                    Me.RaisePropertyChanged("DictionaryValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Mesg() As String
            Get
                Return Me.MesgField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MesgField, value) <> true) Then
                    Me.MesgField = value
                    Me.RaisePropertyChanged("Mesg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org", ConfigurationName:="ClientChargeWS.ClientChargeInputSoap")>  _
    Public Interface ClientChargeInputSoap
        
        'CODEGEN: Generating message contract since element name SystemCode from namespace http://tempuri.org is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WEBSVC.ClientChargeInput.FileClientChargeInput", ReplyAction:="*")>  _
        Function FileClientChargeInput(ByVal request As ClientChargeWS.FileClientChargeInputRequest) As ClientChargeWS.FileClientChargeInputResponse
        
        'CODEGEN: Generating message contract since element name SystemCode from namespace http://tempuri.org is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WEBSVC.ClientChargeInput.GetDictionaryItems", ReplyAction:="*")>  _
        Function GetDictionaryItems(ByVal request As ClientChargeWS.GetDictionaryItemsRequest) As ClientChargeWS.GetDictionaryItemsResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FileClientChargeInputRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FileClientChargeInput", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientChargeWS.FileClientChargeInputRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientChargeWS.FileClientChargeInputRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class FileClientChargeInputRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SystemCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public ClientChargeInputInfo As ClientChargeWS.ClientChargeInputObject
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String, ByVal ClientChargeInputInfo As ClientChargeWS.ClientChargeInputObject)
            MyBase.New
            Me.SystemCode = SystemCode
            Me.UserName = UserName
            Me.Password = Password
            Me.ClientChargeInputInfo = ClientChargeInputInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FileClientChargeInputResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FileClientChargeInputResponse", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientChargeWS.FileClientChargeInputResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientChargeWS.FileClientChargeInputResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class FileClientChargeInputResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FileClientChargeInputResult As ClientChargeWS.WebServiceResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FileClientChargeInputResult As ClientChargeWS.WebServiceResponse)
            MyBase.New
            Me.FileClientChargeInputResult = FileClientChargeInputResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDictionaryItemsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDictionaryItems", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientChargeWS.GetDictionaryItemsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientChargeWS.GetDictionaryItemsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class GetDictionaryItemsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SystemCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String)
            MyBase.New
            Me.SystemCode = SystemCode
            Me.UserName = UserName
            Me.Password = Password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDictionaryItemsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDictionaryItemsResponse", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientChargeWS.GetDictionaryItemsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientChargeWS.GetDictionaryItemsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class GetDictionaryItemsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDictionaryItemsResult As ClientChargeWS.ArrayOfDictionaryItemObjectDictionaryItemObject
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDictionaryItemsResult As ClientChargeWS.ArrayOfDictionaryItemObjectDictionaryItemObject)
            MyBase.New
            Me.GetDictionaryItemsResult = GetDictionaryItemsResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClientChargeInputSoapChannel
        Inherits ClientChargeWS.ClientChargeInputSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClientChargeInputSoapClient
        Inherits System.ServiceModel.ClientBase(Of ClientChargeWS.ClientChargeInputSoap)
        Implements ClientChargeWS.ClientChargeInputSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ClientChargeWS_ClientChargeInputSoap_FileClientChargeInput(ByVal request As ClientChargeWS.FileClientChargeInputRequest) As ClientChargeWS.FileClientChargeInputResponse Implements ClientChargeWS.ClientChargeInputSoap.FileClientChargeInput
            Return MyBase.Channel.FileClientChargeInput(request)
        End Function
        
        Public Function FileClientChargeInput(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String, ByVal ClientChargeInputInfo As ClientChargeWS.ClientChargeInputObject) As ClientChargeWS.WebServiceResponse
            Dim inValue As ClientChargeWS.FileClientChargeInputRequest = New ClientChargeWS.FileClientChargeInputRequest()
            inValue.Body = New ClientChargeWS.FileClientChargeInputRequestBody()
            inValue.Body.SystemCode = SystemCode
            inValue.Body.UserName = UserName
            inValue.Body.Password = Password
            inValue.Body.ClientChargeInputInfo = ClientChargeInputInfo
            Dim retVal As ClientChargeWS.FileClientChargeInputResponse = CType(Me,ClientChargeWS.ClientChargeInputSoap).FileClientChargeInput(inValue)
            Return retVal.Body.FileClientChargeInputResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ClientChargeWS_ClientChargeInputSoap_GetDictionaryItems(ByVal request As ClientChargeWS.GetDictionaryItemsRequest) As ClientChargeWS.GetDictionaryItemsResponse Implements ClientChargeWS.ClientChargeInputSoap.GetDictionaryItems
            Return MyBase.Channel.GetDictionaryItems(request)
        End Function
        
        Public Function GetDictionaryItems(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String) As ClientChargeWS.ArrayOfDictionaryItemObjectDictionaryItemObject
            Dim inValue As ClientChargeWS.GetDictionaryItemsRequest = New ClientChargeWS.GetDictionaryItemsRequest()
            inValue.Body = New ClientChargeWS.GetDictionaryItemsRequestBody()
            inValue.Body.SystemCode = SystemCode
            inValue.Body.UserName = UserName
            inValue.Body.Password = Password
            Dim retVal As ClientChargeWS.GetDictionaryItemsResponse = CType(Me,ClientChargeWS.ClientChargeInputSoap).GetDictionaryItems(inValue)
            Return retVal.Body.GetDictionaryItemsResult
        End Function
    End Class
End Namespace
