//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace NTST.ScriptLinkService.Web.DCIImport {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DCIImportSoap", Namespace="http://localhost")]
    public partial class DCIImport : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImportRecordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DCIImport() {
            this.Url = global::NTST.ScriptLinkService.Web.Properties.Settings.Default.NTST_ScriptLinkService_Web_DCIImport_DCIImport;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImportRecordCompletedEventHandler ImportRecordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WEBSVC.DCIImport.ImportRecord", RequestNamespace="http://localhost", ResponseNamespace="http://localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportRecord(string SystemCode, string UserName, string Password, string record, long filewarnings, [System.Xml.Serialization.XmlIgnoreAttribute()] bool filewarningsSpecified, string recordstream, string resultstream) {
            object[] results = this.Invoke("ImportRecord", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        record,
                        filewarnings,
                        filewarningsSpecified,
                        recordstream,
                        resultstream});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImportRecordAsync(string SystemCode, string UserName, string Password, string record, long filewarnings, bool filewarningsSpecified, string recordstream, string resultstream) {
            this.ImportRecordAsync(SystemCode, UserName, Password, record, filewarnings, filewarningsSpecified, recordstream, resultstream, null);
        }
        
        /// <remarks/>
        public void ImportRecordAsync(string SystemCode, string UserName, string Password, string record, long filewarnings, bool filewarningsSpecified, string recordstream, string resultstream, object userState) {
            if ((this.ImportRecordOperationCompleted == null)) {
                this.ImportRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportRecordOperationCompleted);
            }
            this.InvokeAsync("ImportRecord", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        record,
                        filewarnings,
                        filewarningsSpecified,
                        recordstream,
                        resultstream}, this.ImportRecordOperationCompleted, userState);
        }
        
        private void OnImportRecordOperationCompleted(object arg) {
            if ((this.ImportRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportRecordCompleted(this, new ImportRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ImportRecordCompletedEventHandler(object sender, ImportRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591