//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace NTST.ScriptLinkService.Web.UserManagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesSoap", Namespace="http://tempuri.org")]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActivateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeActivateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoesUserExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserRoleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUserActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServices() {
            this.Url = global::NTST.ScriptLinkService.Web.Properties.Settings.Default.NTST_ScriptLinkService_Web_UserManagement_WebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActivateUserCompletedEventHandler ActivateUserCompleted;
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event DeActivateUserCompletedEventHandler DeActivateUserCompleted;
        
        /// <remarks/>
        public event DoesUserExistCompletedEventHandler DoesUserExistCompleted;
        
        /// <remarks/>
        public event GeneratePasswordCompletedEventHandler GeneratePasswordCompleted;
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        public event GetUserRoleListCompletedEventHandler GetUserRoleListCompleted;
        
        /// <remarks/>
        public event IsUserActiveCompletedEventHandler IsUserActiveCompleted;
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.ActivateUser", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse ActivateUser(string SystemCode, string UserName, string Password, string User) {
            object[] results = this.Invoke("ActivateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateUserAsync(string SystemCode, string UserName, string Password, string User) {
            this.ActivateUserAsync(SystemCode, UserName, Password, User, null);
        }
        
        /// <remarks/>
        public void ActivateUserAsync(string SystemCode, string UserName, string Password, string User, object userState) {
            if ((this.ActivateUserOperationCompleted == null)) {
                this.ActivateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateUserOperationCompleted);
            }
            this.InvokeAsync("ActivateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User}, this.ActivateUserOperationCompleted, userState);
        }
        
        private void OnActivateUserOperationCompleted(object arg) {
            if ((this.ActivateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateUserCompleted(this, new ActivateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.CreateUser", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse CreateUser(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        UserDefinition});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition) {
            this.CreateUserAsync(SystemCode, UserName, Password, UserDefinition, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        UserDefinition}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.DeActivateUser", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse DeActivateUser(string SystemCode, string UserName, string Password, string User) {
            object[] results = this.Invoke("DeActivateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeActivateUserAsync(string SystemCode, string UserName, string Password, string User) {
            this.DeActivateUserAsync(SystemCode, UserName, Password, User, null);
        }
        
        /// <remarks/>
        public void DeActivateUserAsync(string SystemCode, string UserName, string Password, string User, object userState) {
            if ((this.DeActivateUserOperationCompleted == null)) {
                this.DeActivateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeActivateUserOperationCompleted);
            }
            this.InvokeAsync("DeActivateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User}, this.DeActivateUserOperationCompleted, userState);
        }
        
        private void OnDeActivateUserOperationCompleted(object arg) {
            if ((this.DeActivateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeActivateUserCompleted(this, new DeActivateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.DoesUserExist", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse DoesUserExist(string SystemCode, string UserName, string Password, string User) {
            object[] results = this.Invoke("DoesUserExist", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DoesUserExistAsync(string SystemCode, string UserName, string Password, string User) {
            this.DoesUserExistAsync(SystemCode, UserName, Password, User, null);
        }
        
        /// <remarks/>
        public void DoesUserExistAsync(string SystemCode, string UserName, string Password, string User, object userState) {
            if ((this.DoesUserExistOperationCompleted == null)) {
                this.DoesUserExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoesUserExistOperationCompleted);
            }
            this.InvokeAsync("DoesUserExist", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User}, this.DoesUserExistOperationCompleted, userState);
        }
        
        private void OnDoesUserExistOperationCompleted(object arg) {
            if ((this.DoesUserExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoesUserExistCompleted(this, new DoesUserExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.GeneratePassword", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse GeneratePassword(string SystemCode, string UserName, string Password, string User) {
            object[] results = this.Invoke("GeneratePassword", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePasswordAsync(string SystemCode, string UserName, string Password, string User) {
            this.GeneratePasswordAsync(SystemCode, UserName, Password, User, null);
        }
        
        /// <remarks/>
        public void GeneratePasswordAsync(string SystemCode, string UserName, string Password, string User, object userState) {
            if ((this.GeneratePasswordOperationCompleted == null)) {
                this.GeneratePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePasswordOperationCompleted);
            }
            this.InvokeAsync("GeneratePassword", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User}, this.GeneratePasswordOperationCompleted, userState);
        }
        
        private void OnGeneratePasswordOperationCompleted(object arg) {
            if ((this.GeneratePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePasswordCompleted(this, new GeneratePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.GetUserRoleList", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserRoleObject[] GetUserRoleList(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetUserRoleList", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((UserRoleObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserRoleListAsync(string SystemCode, string UserName, string Password) {
            this.GetUserRoleListAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetUserRoleListAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetUserRoleListOperationCompleted == null)) {
                this.GetUserRoleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserRoleListOperationCompleted);
            }
            this.InvokeAsync("GetUserRoleList", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetUserRoleListOperationCompleted, userState);
        }
        
        private void OnGetUserRoleListOperationCompleted(object arg) {
            if ((this.GetUserRoleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserRoleListCompleted(this, new GetUserRoleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.IsUserActive", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse IsUserActive(string SystemCode, string UserName, string Password, string User) {
            object[] results = this.Invoke("IsUserActive", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IsUserActiveAsync(string SystemCode, string UserName, string Password, string User) {
            this.IsUserActiveAsync(SystemCode, UserName, Password, User, null);
        }
        
        /// <remarks/>
        public void IsUserActiveAsync(string SystemCode, string UserName, string Password, string User, object userState) {
            if ((this.IsUserActiveOperationCompleted == null)) {
                this.IsUserActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserActiveOperationCompleted);
            }
            this.InvokeAsync("IsUserActive", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        User}, this.IsUserActiveOperationCompleted, userState);
        }
        
        private void OnIsUserActiveOperationCompleted(object arg) {
            if ((this.IsUserActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUserActiveCompleted(this, new IsUserActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.UserManagement.UpdateUser", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse UpdateUser(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        UserDefinition});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserAsync(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition) {
            this.UpdateUserAsync(SystemCode, UserName, Password, UserDefinition, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(string SystemCode, string UserName, string Password, UserDefinitionObject UserDefinition, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        UserDefinition}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class UserRoleObject {
        
        private string mesgField;
        
        private string roleDescriptionField;
        
        private string roleIdField;
        
        private string statusField;
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string RoleDescription {
            get {
                return this.roleDescriptionField;
            }
            set {
                this.roleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class UserDefinitionObject {
        
        private string allowUserRenewalField;
        
        private string allowUserToModPrtFontsField;
        
        private string isUserAStaffMemberField;
        
        private string isUserAUnitField;
        
        private string isUserSystemAdministratorField;
        
        private long passwordTermDurationDaysField;
        
        private bool passwordTermDurationDaysFieldSpecified;
        
        private string preventUserFromAppLogoutField;
        
        private string preventUsrAcsToNonCaseCltField;
        
        private string promptForUsernameAtOptEntField;
        
        private long reminderNoticeNumDaysField;
        
        private bool reminderNoticeNumDaysFieldSpecified;
        
        private string reqFilingAuthForAppOptsField;
        
        private string staffIdField;
        
        private string unitIdField;
        
        private string userDescriptionField;
        
        private string userIdField;
        
        private string userRolesField;
        
        private string userSecurityLevelField;
        
        private long userTimeoutSecondField;
        
        private bool userTimeoutSecondFieldSpecified;
        
        private string warnNonCaseloadAccessField;
        
        /// <remarks/>
        public string AllowUserRenewal {
            get {
                return this.allowUserRenewalField;
            }
            set {
                this.allowUserRenewalField = value;
            }
        }
        
        /// <remarks/>
        public string AllowUserToModPrtFonts {
            get {
                return this.allowUserToModPrtFontsField;
            }
            set {
                this.allowUserToModPrtFontsField = value;
            }
        }
        
        /// <remarks/>
        public string IsUserAStaffMember {
            get {
                return this.isUserAStaffMemberField;
            }
            set {
                this.isUserAStaffMemberField = value;
            }
        }
        
        /// <remarks/>
        public string IsUserAUnit {
            get {
                return this.isUserAUnitField;
            }
            set {
                this.isUserAUnitField = value;
            }
        }
        
        /// <remarks/>
        public string IsUserSystemAdministrator {
            get {
                return this.isUserSystemAdministratorField;
            }
            set {
                this.isUserSystemAdministratorField = value;
            }
        }
        
        /// <remarks/>
        public long PasswordTermDurationDays {
            get {
                return this.passwordTermDurationDaysField;
            }
            set {
                this.passwordTermDurationDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PasswordTermDurationDaysSpecified {
            get {
                return this.passwordTermDurationDaysFieldSpecified;
            }
            set {
                this.passwordTermDurationDaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PreventUserFromAppLogout {
            get {
                return this.preventUserFromAppLogoutField;
            }
            set {
                this.preventUserFromAppLogoutField = value;
            }
        }
        
        /// <remarks/>
        public string PreventUsrAcsToNonCaseClt {
            get {
                return this.preventUsrAcsToNonCaseCltField;
            }
            set {
                this.preventUsrAcsToNonCaseCltField = value;
            }
        }
        
        /// <remarks/>
        public string PromptForUsernameAtOptEnt {
            get {
                return this.promptForUsernameAtOptEntField;
            }
            set {
                this.promptForUsernameAtOptEntField = value;
            }
        }
        
        /// <remarks/>
        public long ReminderNoticeNumDays {
            get {
                return this.reminderNoticeNumDaysField;
            }
            set {
                this.reminderNoticeNumDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReminderNoticeNumDaysSpecified {
            get {
                return this.reminderNoticeNumDaysFieldSpecified;
            }
            set {
                this.reminderNoticeNumDaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReqFilingAuthForAppOpts {
            get {
                return this.reqFilingAuthForAppOptsField;
            }
            set {
                this.reqFilingAuthForAppOptsField = value;
            }
        }
        
        /// <remarks/>
        public string StaffId {
            get {
                return this.staffIdField;
            }
            set {
                this.staffIdField = value;
            }
        }
        
        /// <remarks/>
        public string UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserDescription {
            get {
                return this.userDescriptionField;
            }
            set {
                this.userDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserRoles {
            get {
                return this.userRolesField;
            }
            set {
                this.userRolesField = value;
            }
        }
        
        /// <remarks/>
        public string UserSecurityLevel {
            get {
                return this.userSecurityLevelField;
            }
            set {
                this.userSecurityLevelField = value;
            }
        }
        
        /// <remarks/>
        public long UserTimeoutSecond {
            get {
                return this.userTimeoutSecondField;
            }
            set {
                this.userTimeoutSecondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserTimeoutSecondSpecified {
            get {
                return this.userTimeoutSecondFieldSpecified;
            }
            set {
                this.userTimeoutSecondFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string WarnNonCaseloadAccess {
            get {
                return this.warnNonCaseloadAccessField;
            }
            set {
                this.warnNonCaseloadAccessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActivateUserCompletedEventHandler(object sender, ActivateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeActivateUserCompletedEventHandler(object sender, DeActivateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeActivateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeActivateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DoesUserExistCompletedEventHandler(object sender, DoesUserExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoesUserExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoesUserExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GeneratePasswordCompletedEventHandler(object sender, GeneratePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserRoleListCompletedEventHandler(object sender, GetUserRoleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserRoleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserRoleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserRoleObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserRoleObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsUserActiveCompletedEventHandler(object sender, IsUserActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUserActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUserActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591