//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace NTST.ScriptLinkService.Web.ProgramTransfer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProgramTransferSoap", Namespace="http://tempuri.org")]
    public partial class ProgramTransfer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransferProgramOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProgramTransfer() {
            this.Url = global::NTST.ScriptLinkService.Web.Properties.Settings.Default.NTST_ScriptLinkService_Web_ProgramTransfer_ProgramTransfer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        public event TransferProgramCompletedEventHandler TransferProgramCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ProgramTransfer.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ProgramTransfer.TransferProgram", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse TransferProgram(string SystemCode, string UserName, string Password, ProgramTransferObject ProgramTransferInfo, string ClientID, string EpisodeNumber) {
            object[] results = this.Invoke("TransferProgram", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ProgramTransferInfo,
                        ClientID,
                        EpisodeNumber});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TransferProgramAsync(string SystemCode, string UserName, string Password, ProgramTransferObject ProgramTransferInfo, string ClientID, string EpisodeNumber) {
            this.TransferProgramAsync(SystemCode, UserName, Password, ProgramTransferInfo, ClientID, EpisodeNumber, null);
        }
        
        /// <remarks/>
        public void TransferProgramAsync(string SystemCode, string UserName, string Password, ProgramTransferObject ProgramTransferInfo, string ClientID, string EpisodeNumber, object userState) {
            if ((this.TransferProgramOperationCompleted == null)) {
                this.TransferProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransferProgramOperationCompleted);
            }
            this.InvokeAsync("TransferProgram", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ProgramTransferInfo,
                        ClientID,
                        EpisodeNumber}, this.TransferProgramOperationCompleted, userState);
        }
        
        private void OnTransferProgramOperationCompleted(object arg) {
            if ((this.TransferProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransferProgramCompleted(this, new TransferProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ProgramTransferObject {
        
        private string admissionChargeCodeField;
        
        private string bedField;
        
        private string dailyChargeCodeField;
        
        private string dailyChargeCode2Field;
        
        private string dailyChargeCode3Field;
        
        private string dailyChargeCode4Field;
        
        private string dailyChargeCode5Field;
        
        private System.DateTime dateOfTransferField;
        
        private bool dateOfTransferFieldSpecified;
        
        private string partialHospitalBillingCodeField;
        
        private string partialHospitalBillingCode2Field;
        
        private string partialHospitilizationDaysField;
        
        private string partialHospitilizationHoursField;
        
        private string programField;
        
        private string roomField;
        
        private string roomAndBoardBillingCodeField;
        
        private string timeOfTransferField;
        
        private string typeOfTransferField;
        
        private string unitField;
        
        /// <remarks/>
        public string AdmissionChargeCode {
            get {
                return this.admissionChargeCodeField;
            }
            set {
                this.admissionChargeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bed {
            get {
                return this.bedField;
            }
            set {
                this.bedField = value;
            }
        }
        
        /// <remarks/>
        public string DailyChargeCode {
            get {
                return this.dailyChargeCodeField;
            }
            set {
                this.dailyChargeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DailyChargeCode2 {
            get {
                return this.dailyChargeCode2Field;
            }
            set {
                this.dailyChargeCode2Field = value;
            }
        }
        
        /// <remarks/>
        public string DailyChargeCode3 {
            get {
                return this.dailyChargeCode3Field;
            }
            set {
                this.dailyChargeCode3Field = value;
            }
        }
        
        /// <remarks/>
        public string DailyChargeCode4 {
            get {
                return this.dailyChargeCode4Field;
            }
            set {
                this.dailyChargeCode4Field = value;
            }
        }
        
        /// <remarks/>
        public string DailyChargeCode5 {
            get {
                return this.dailyChargeCode5Field;
            }
            set {
                this.dailyChargeCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfTransfer {
            get {
                return this.dateOfTransferField;
            }
            set {
                this.dateOfTransferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfTransferSpecified {
            get {
                return this.dateOfTransferFieldSpecified;
            }
            set {
                this.dateOfTransferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PartialHospitalBillingCode {
            get {
                return this.partialHospitalBillingCodeField;
            }
            set {
                this.partialHospitalBillingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PartialHospitalBillingCode2 {
            get {
                return this.partialHospitalBillingCode2Field;
            }
            set {
                this.partialHospitalBillingCode2Field = value;
            }
        }
        
        /// <remarks/>
        public string PartialHospitilizationDays {
            get {
                return this.partialHospitilizationDaysField;
            }
            set {
                this.partialHospitilizationDaysField = value;
            }
        }
        
        /// <remarks/>
        public string PartialHospitilizationHours {
            get {
                return this.partialHospitilizationHoursField;
            }
            set {
                this.partialHospitilizationHoursField = value;
            }
        }
        
        /// <remarks/>
        public string Program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
        
        /// <remarks/>
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string RoomAndBoardBillingCode {
            get {
                return this.roomAndBoardBillingCodeField;
            }
            set {
                this.roomAndBoardBillingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TimeOfTransfer {
            get {
                return this.timeOfTransferField;
            }
            set {
                this.timeOfTransferField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfTransfer {
            get {
                return this.typeOfTransferField;
            }
            set {
                this.typeOfTransferField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TransferProgramCompletedEventHandler(object sender, TransferProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransferProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591