'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ClientDemWS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfDictionaryItemObjectDictionaryItemObject", [Namespace]:="http://tempuri.org", ItemName:="DictionaryItemObject"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfDictionaryItemObjectDictionaryItemObject
        Inherits System.Collections.Generic.List(Of ClientDemWS.DictionaryItemObject)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DictionaryItemObject", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DictionaryItemObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryFieldDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryUniqueIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DictionaryValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MesgField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryCode() As String
            Get
                Return Me.DictionaryCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryCodeField, value) <> true) Then
                    Me.DictionaryCodeField = value
                    Me.RaisePropertyChanged("DictionaryCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryFieldDescription() As String
            Get
                Return Me.DictionaryFieldDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryFieldDescriptionField, value) <> true) Then
                    Me.DictionaryFieldDescriptionField = value
                    Me.RaisePropertyChanged("DictionaryFieldDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryUniqueId() As String
            Get
                Return Me.DictionaryUniqueIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryUniqueIdField, value) <> true) Then
                    Me.DictionaryUniqueIdField = value
                    Me.RaisePropertyChanged("DictionaryUniqueId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DictionaryValue() As String
            Get
                Return Me.DictionaryValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DictionaryValueField, value) <> true) Then
                    Me.DictionaryValueField = value
                    Me.RaisePropertyChanged("DictionaryValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Mesg() As String
            Get
                Return Me.MesgField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MesgField, value) <> true) Then
                    Me.MesgField = value
                    Me.RaisePropertyChanged("Mesg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientDemographicsObject", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClientDemographicsObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AliasField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias10Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias6Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias7Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias8Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Alias9Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CitizenshipField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressCityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressCountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressCountyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressStateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressStreetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressStreet2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientAddressZipcodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientCellPhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressCityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressCountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressStateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressStreetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressStreet2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfAddressZipcodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientConfPhoneNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientFirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientHomePhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientLastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressCityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressCountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressStateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressStreetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressStreet2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMailAddressZipcodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientMiddleNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientPrefixField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientRaceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientSuffixField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientWorkPhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryOfOriginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOfBirthField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EducationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmploymentStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EthnicOriginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FacilityChartNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaidenNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaritalStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OccupationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtherEthnicOriginsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtherRacesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PlaceOfBirthField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreferredProvidersEthnicOriginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreferredProvidersSexField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrimaryLanguageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReligionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDate1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDate2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDate3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDate4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDate5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict10Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict6Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict7Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict8Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsDict9Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText201Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText202Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText203Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText204Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText205Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText401Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText402Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText403Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText404Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsFreeText405Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsMult1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsMult2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsMult3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsMult4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsMult5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPhone1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPhone2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPhone3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPhone4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPhone5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPractitioner1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPractitioner2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPractitioner3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPractitioner4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsPractitioner5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsScrollFreeText1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsScrollFreeText2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsScrollFreeText3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsScrollFreeText4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsScrollFreeText5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsTime1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsTime2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsTime3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsTime4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSDemographicsTime5Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SocialSecurityNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SocialSecurityNumber2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SocialSecurityNumber3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SocialSecurityNumber4Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property [Alias]() As String
            Get
                Return Me.AliasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AliasField, value) <> true) Then
                    Me.AliasField = value
                    Me.RaisePropertyChanged("Alias")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias10() As String
            Get
                Return Me.Alias10Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias10Field, value) <> true) Then
                    Me.Alias10Field = value
                    Me.RaisePropertyChanged("Alias10")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias2() As String
            Get
                Return Me.Alias2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias2Field, value) <> true) Then
                    Me.Alias2Field = value
                    Me.RaisePropertyChanged("Alias2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias3() As String
            Get
                Return Me.Alias3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias3Field, value) <> true) Then
                    Me.Alias3Field = value
                    Me.RaisePropertyChanged("Alias3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias4() As String
            Get
                Return Me.Alias4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias4Field, value) <> true) Then
                    Me.Alias4Field = value
                    Me.RaisePropertyChanged("Alias4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias5() As String
            Get
                Return Me.Alias5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias5Field, value) <> true) Then
                    Me.Alias5Field = value
                    Me.RaisePropertyChanged("Alias5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias6() As String
            Get
                Return Me.Alias6Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias6Field, value) <> true) Then
                    Me.Alias6Field = value
                    Me.RaisePropertyChanged("Alias6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias7() As String
            Get
                Return Me.Alias7Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias7Field, value) <> true) Then
                    Me.Alias7Field = value
                    Me.RaisePropertyChanged("Alias7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias8() As String
            Get
                Return Me.Alias8Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias8Field, value) <> true) Then
                    Me.Alias8Field = value
                    Me.RaisePropertyChanged("Alias8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Alias9() As String
            Get
                Return Me.Alias9Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Alias9Field, value) <> true) Then
                    Me.Alias9Field = value
                    Me.RaisePropertyChanged("Alias9")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Citizenship() As String
            Get
                Return Me.CitizenshipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CitizenshipField, value) <> true) Then
                    Me.CitizenshipField = value
                    Me.RaisePropertyChanged("Citizenship")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressCity() As String
            Get
                Return Me.ClientAddressCityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressCityField, value) <> true) Then
                    Me.ClientAddressCityField = value
                    Me.RaisePropertyChanged("ClientAddressCity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressCountry() As String
            Get
                Return Me.ClientAddressCountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressCountryField, value) <> true) Then
                    Me.ClientAddressCountryField = value
                    Me.RaisePropertyChanged("ClientAddressCountry")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressCounty() As String
            Get
                Return Me.ClientAddressCountyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressCountyField, value) <> true) Then
                    Me.ClientAddressCountyField = value
                    Me.RaisePropertyChanged("ClientAddressCounty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressState() As String
            Get
                Return Me.ClientAddressStateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressStateField, value) <> true) Then
                    Me.ClientAddressStateField = value
                    Me.RaisePropertyChanged("ClientAddressState")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressStreet() As String
            Get
                Return Me.ClientAddressStreetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressStreetField, value) <> true) Then
                    Me.ClientAddressStreetField = value
                    Me.RaisePropertyChanged("ClientAddressStreet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressStreet2() As String
            Get
                Return Me.ClientAddressStreet2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressStreet2Field, value) <> true) Then
                    Me.ClientAddressStreet2Field = value
                    Me.RaisePropertyChanged("ClientAddressStreet2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientAddressZipcode() As String
            Get
                Return Me.ClientAddressZipcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientAddressZipcodeField, value) <> true) Then
                    Me.ClientAddressZipcodeField = value
                    Me.RaisePropertyChanged("ClientAddressZipcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientCellPhone() As String
            Get
                Return Me.ClientCellPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientCellPhoneField, value) <> true) Then
                    Me.ClientCellPhoneField = value
                    Me.RaisePropertyChanged("ClientCellPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressCity() As String
            Get
                Return Me.ClientConfAddressCityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressCityField, value) <> true) Then
                    Me.ClientConfAddressCityField = value
                    Me.RaisePropertyChanged("ClientConfAddressCity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressCountry() As String
            Get
                Return Me.ClientConfAddressCountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressCountryField, value) <> true) Then
                    Me.ClientConfAddressCountryField = value
                    Me.RaisePropertyChanged("ClientConfAddressCountry")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressState() As String
            Get
                Return Me.ClientConfAddressStateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressStateField, value) <> true) Then
                    Me.ClientConfAddressStateField = value
                    Me.RaisePropertyChanged("ClientConfAddressState")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressStreet() As String
            Get
                Return Me.ClientConfAddressStreetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressStreetField, value) <> true) Then
                    Me.ClientConfAddressStreetField = value
                    Me.RaisePropertyChanged("ClientConfAddressStreet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressStreet2() As String
            Get
                Return Me.ClientConfAddressStreet2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressStreet2Field, value) <> true) Then
                    Me.ClientConfAddressStreet2Field = value
                    Me.RaisePropertyChanged("ClientConfAddressStreet2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfAddressZipcode() As String
            Get
                Return Me.ClientConfAddressZipcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfAddressZipcodeField, value) <> true) Then
                    Me.ClientConfAddressZipcodeField = value
                    Me.RaisePropertyChanged("ClientConfAddressZipcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientConfPhoneNumber() As String
            Get
                Return Me.ClientConfPhoneNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientConfPhoneNumberField, value) <> true) Then
                    Me.ClientConfPhoneNumberField = value
                    Me.RaisePropertyChanged("ClientConfPhoneNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientFirstName() As String
            Get
                Return Me.ClientFirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientFirstNameField, value) <> true) Then
                    Me.ClientFirstNameField = value
                    Me.RaisePropertyChanged("ClientFirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientHomePhone() As String
            Get
                Return Me.ClientHomePhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientHomePhoneField, value) <> true) Then
                    Me.ClientHomePhoneField = value
                    Me.RaisePropertyChanged("ClientHomePhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientLastName() As String
            Get
                Return Me.ClientLastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientLastNameField, value) <> true) Then
                    Me.ClientLastNameField = value
                    Me.RaisePropertyChanged("ClientLastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressCity() As String
            Get
                Return Me.ClientMailAddressCityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressCityField, value) <> true) Then
                    Me.ClientMailAddressCityField = value
                    Me.RaisePropertyChanged("ClientMailAddressCity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressCountry() As String
            Get
                Return Me.ClientMailAddressCountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressCountryField, value) <> true) Then
                    Me.ClientMailAddressCountryField = value
                    Me.RaisePropertyChanged("ClientMailAddressCountry")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressState() As String
            Get
                Return Me.ClientMailAddressStateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressStateField, value) <> true) Then
                    Me.ClientMailAddressStateField = value
                    Me.RaisePropertyChanged("ClientMailAddressState")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressStreet() As String
            Get
                Return Me.ClientMailAddressStreetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressStreetField, value) <> true) Then
                    Me.ClientMailAddressStreetField = value
                    Me.RaisePropertyChanged("ClientMailAddressStreet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressStreet2() As String
            Get
                Return Me.ClientMailAddressStreet2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressStreet2Field, value) <> true) Then
                    Me.ClientMailAddressStreet2Field = value
                    Me.RaisePropertyChanged("ClientMailAddressStreet2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMailAddressZipcode() As String
            Get
                Return Me.ClientMailAddressZipcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMailAddressZipcodeField, value) <> true) Then
                    Me.ClientMailAddressZipcodeField = value
                    Me.RaisePropertyChanged("ClientMailAddressZipcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientMiddleName() As String
            Get
                Return Me.ClientMiddleNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientMiddleNameField, value) <> true) Then
                    Me.ClientMiddleNameField = value
                    Me.RaisePropertyChanged("ClientMiddleName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientName() As String
            Get
                Return Me.ClientNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientNameField, value) <> true) Then
                    Me.ClientNameField = value
                    Me.RaisePropertyChanged("ClientName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientPrefix() As String
            Get
                Return Me.ClientPrefixField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientPrefixField, value) <> true) Then
                    Me.ClientPrefixField = value
                    Me.RaisePropertyChanged("ClientPrefix")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientRace() As String
            Get
                Return Me.ClientRaceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientRaceField, value) <> true) Then
                    Me.ClientRaceField = value
                    Me.RaisePropertyChanged("ClientRace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientSuffix() As String
            Get
                Return Me.ClientSuffixField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientSuffixField, value) <> true) Then
                    Me.ClientSuffixField = value
                    Me.RaisePropertyChanged("ClientSuffix")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClientWorkPhone() As String
            Get
                Return Me.ClientWorkPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientWorkPhoneField, value) <> true) Then
                    Me.ClientWorkPhoneField = value
                    Me.RaisePropertyChanged("ClientWorkPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CountryOfOrigin() As String
            Get
                Return Me.CountryOfOriginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryOfOriginField, value) <> true) Then
                    Me.CountryOfOriginField = value
                    Me.RaisePropertyChanged("CountryOfOrigin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DateOfBirth() As String
            Get
                Return Me.DateOfBirthField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateOfBirthField, value) <> true) Then
                    Me.DateOfBirthField = value
                    Me.RaisePropertyChanged("DateOfBirth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Education() As String
            Get
                Return Me.EducationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EducationField, value) <> true) Then
                    Me.EducationField = value
                    Me.RaisePropertyChanged("Education")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property EmploymentStatus() As String
            Get
                Return Me.EmploymentStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmploymentStatusField, value) <> true) Then
                    Me.EmploymentStatusField = value
                    Me.RaisePropertyChanged("EmploymentStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property EthnicOrigin() As String
            Get
                Return Me.EthnicOriginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EthnicOriginField, value) <> true) Then
                    Me.EthnicOriginField = value
                    Me.RaisePropertyChanged("EthnicOrigin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property FacilityChartNumber() As String
            Get
                Return Me.FacilityChartNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FacilityChartNumberField, value) <> true) Then
                    Me.FacilityChartNumberField = value
                    Me.RaisePropertyChanged("FacilityChartNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MaidenName() As String
            Get
                Return Me.MaidenNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaidenNameField, value) <> true) Then
                    Me.MaidenNameField = value
                    Me.RaisePropertyChanged("MaidenName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MaritalStatus() As String
            Get
                Return Me.MaritalStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaritalStatusField, value) <> true) Then
                    Me.MaritalStatusField = value
                    Me.RaisePropertyChanged("MaritalStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Occupation() As String
            Get
                Return Me.OccupationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OccupationField, value) <> true) Then
                    Me.OccupationField = value
                    Me.RaisePropertyChanged("Occupation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OtherEthnicOrigins() As String
            Get
                Return Me.OtherEthnicOriginsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtherEthnicOriginsField, value) <> true) Then
                    Me.OtherEthnicOriginsField = value
                    Me.RaisePropertyChanged("OtherEthnicOrigins")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OtherRaces() As String
            Get
                Return Me.OtherRacesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtherRacesField, value) <> true) Then
                    Me.OtherRacesField = value
                    Me.RaisePropertyChanged("OtherRaces")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PlaceOfBirth() As String
            Get
                Return Me.PlaceOfBirthField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlaceOfBirthField, value) <> true) Then
                    Me.PlaceOfBirthField = value
                    Me.RaisePropertyChanged("PlaceOfBirth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PreferredProvidersEthnicOrigin() As String
            Get
                Return Me.PreferredProvidersEthnicOriginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PreferredProvidersEthnicOriginField, value) <> true) Then
                    Me.PreferredProvidersEthnicOriginField = value
                    Me.RaisePropertyChanged("PreferredProvidersEthnicOrigin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PreferredProvidersSex() As String
            Get
                Return Me.PreferredProvidersSexField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PreferredProvidersSexField, value) <> true) Then
                    Me.PreferredProvidersSexField = value
                    Me.RaisePropertyChanged("PreferredProvidersSex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PrimaryLanguage() As String
            Get
                Return Me.PrimaryLanguageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrimaryLanguageField, value) <> true) Then
                    Me.PrimaryLanguageField = value
                    Me.RaisePropertyChanged("PrimaryLanguage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Religion() As String
            Get
                Return Me.ReligionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReligionField, value) <> true) Then
                    Me.ReligionField = value
                    Me.RaisePropertyChanged("Religion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDate1() As String
            Get
                Return Me.SSDemographicsDate1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDate1Field, value) <> true) Then
                    Me.SSDemographicsDate1Field = value
                    Me.RaisePropertyChanged("SSDemographicsDate1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDate2() As String
            Get
                Return Me.SSDemographicsDate2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDate2Field, value) <> true) Then
                    Me.SSDemographicsDate2Field = value
                    Me.RaisePropertyChanged("SSDemographicsDate2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDate3() As String
            Get
                Return Me.SSDemographicsDate3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDate3Field, value) <> true) Then
                    Me.SSDemographicsDate3Field = value
                    Me.RaisePropertyChanged("SSDemographicsDate3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDate4() As String
            Get
                Return Me.SSDemographicsDate4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDate4Field, value) <> true) Then
                    Me.SSDemographicsDate4Field = value
                    Me.RaisePropertyChanged("SSDemographicsDate4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDate5() As String
            Get
                Return Me.SSDemographicsDate5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDate5Field, value) <> true) Then
                    Me.SSDemographicsDate5Field = value
                    Me.RaisePropertyChanged("SSDemographicsDate5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict1() As String
            Get
                Return Me.SSDemographicsDict1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict1Field, value) <> true) Then
                    Me.SSDemographicsDict1Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict10() As String
            Get
                Return Me.SSDemographicsDict10Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict10Field, value) <> true) Then
                    Me.SSDemographicsDict10Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict10")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict2() As String
            Get
                Return Me.SSDemographicsDict2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict2Field, value) <> true) Then
                    Me.SSDemographicsDict2Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict3() As String
            Get
                Return Me.SSDemographicsDict3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict3Field, value) <> true) Then
                    Me.SSDemographicsDict3Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict4() As String
            Get
                Return Me.SSDemographicsDict4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict4Field, value) <> true) Then
                    Me.SSDemographicsDict4Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict5() As String
            Get
                Return Me.SSDemographicsDict5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict5Field, value) <> true) Then
                    Me.SSDemographicsDict5Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict6() As String
            Get
                Return Me.SSDemographicsDict6Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict6Field, value) <> true) Then
                    Me.SSDemographicsDict6Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict7() As String
            Get
                Return Me.SSDemographicsDict7Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict7Field, value) <> true) Then
                    Me.SSDemographicsDict7Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict8() As String
            Get
                Return Me.SSDemographicsDict8Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict8Field, value) <> true) Then
                    Me.SSDemographicsDict8Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsDict9() As String
            Get
                Return Me.SSDemographicsDict9Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsDict9Field, value) <> true) Then
                    Me.SSDemographicsDict9Field = value
                    Me.RaisePropertyChanged("SSDemographicsDict9")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText201() As String
            Get
                Return Me.SSDemographicsFreeText201Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText201Field, value) <> true) Then
                    Me.SSDemographicsFreeText201Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText201")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText202() As String
            Get
                Return Me.SSDemographicsFreeText202Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText202Field, value) <> true) Then
                    Me.SSDemographicsFreeText202Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText202")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText203() As String
            Get
                Return Me.SSDemographicsFreeText203Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText203Field, value) <> true) Then
                    Me.SSDemographicsFreeText203Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText203")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText204() As String
            Get
                Return Me.SSDemographicsFreeText204Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText204Field, value) <> true) Then
                    Me.SSDemographicsFreeText204Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText204")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText205() As String
            Get
                Return Me.SSDemographicsFreeText205Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText205Field, value) <> true) Then
                    Me.SSDemographicsFreeText205Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText205")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText401() As String
            Get
                Return Me.SSDemographicsFreeText401Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText401Field, value) <> true) Then
                    Me.SSDemographicsFreeText401Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText401")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText402() As String
            Get
                Return Me.SSDemographicsFreeText402Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText402Field, value) <> true) Then
                    Me.SSDemographicsFreeText402Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText402")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText403() As String
            Get
                Return Me.SSDemographicsFreeText403Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText403Field, value) <> true) Then
                    Me.SSDemographicsFreeText403Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText403")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText404() As String
            Get
                Return Me.SSDemographicsFreeText404Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText404Field, value) <> true) Then
                    Me.SSDemographicsFreeText404Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText404")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsFreeText405() As String
            Get
                Return Me.SSDemographicsFreeText405Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsFreeText405Field, value) <> true) Then
                    Me.SSDemographicsFreeText405Field = value
                    Me.RaisePropertyChanged("SSDemographicsFreeText405")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsMult1() As String
            Get
                Return Me.SSDemographicsMult1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsMult1Field, value) <> true) Then
                    Me.SSDemographicsMult1Field = value
                    Me.RaisePropertyChanged("SSDemographicsMult1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsMult2() As String
            Get
                Return Me.SSDemographicsMult2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsMult2Field, value) <> true) Then
                    Me.SSDemographicsMult2Field = value
                    Me.RaisePropertyChanged("SSDemographicsMult2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsMult3() As String
            Get
                Return Me.SSDemographicsMult3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsMult3Field, value) <> true) Then
                    Me.SSDemographicsMult3Field = value
                    Me.RaisePropertyChanged("SSDemographicsMult3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsMult4() As String
            Get
                Return Me.SSDemographicsMult4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsMult4Field, value) <> true) Then
                    Me.SSDemographicsMult4Field = value
                    Me.RaisePropertyChanged("SSDemographicsMult4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsMult5() As String
            Get
                Return Me.SSDemographicsMult5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsMult5Field, value) <> true) Then
                    Me.SSDemographicsMult5Field = value
                    Me.RaisePropertyChanged("SSDemographicsMult5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPhone1() As String
            Get
                Return Me.SSDemographicsPhone1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPhone1Field, value) <> true) Then
                    Me.SSDemographicsPhone1Field = value
                    Me.RaisePropertyChanged("SSDemographicsPhone1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPhone2() As String
            Get
                Return Me.SSDemographicsPhone2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPhone2Field, value) <> true) Then
                    Me.SSDemographicsPhone2Field = value
                    Me.RaisePropertyChanged("SSDemographicsPhone2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPhone3() As String
            Get
                Return Me.SSDemographicsPhone3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPhone3Field, value) <> true) Then
                    Me.SSDemographicsPhone3Field = value
                    Me.RaisePropertyChanged("SSDemographicsPhone3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPhone4() As String
            Get
                Return Me.SSDemographicsPhone4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPhone4Field, value) <> true) Then
                    Me.SSDemographicsPhone4Field = value
                    Me.RaisePropertyChanged("SSDemographicsPhone4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPhone5() As String
            Get
                Return Me.SSDemographicsPhone5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPhone5Field, value) <> true) Then
                    Me.SSDemographicsPhone5Field = value
                    Me.RaisePropertyChanged("SSDemographicsPhone5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPractitioner1() As String
            Get
                Return Me.SSDemographicsPractitioner1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPractitioner1Field, value) <> true) Then
                    Me.SSDemographicsPractitioner1Field = value
                    Me.RaisePropertyChanged("SSDemographicsPractitioner1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPractitioner2() As String
            Get
                Return Me.SSDemographicsPractitioner2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPractitioner2Field, value) <> true) Then
                    Me.SSDemographicsPractitioner2Field = value
                    Me.RaisePropertyChanged("SSDemographicsPractitioner2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPractitioner3() As String
            Get
                Return Me.SSDemographicsPractitioner3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPractitioner3Field, value) <> true) Then
                    Me.SSDemographicsPractitioner3Field = value
                    Me.RaisePropertyChanged("SSDemographicsPractitioner3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPractitioner4() As String
            Get
                Return Me.SSDemographicsPractitioner4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPractitioner4Field, value) <> true) Then
                    Me.SSDemographicsPractitioner4Field = value
                    Me.RaisePropertyChanged("SSDemographicsPractitioner4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsPractitioner5() As String
            Get
                Return Me.SSDemographicsPractitioner5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsPractitioner5Field, value) <> true) Then
                    Me.SSDemographicsPractitioner5Field = value
                    Me.RaisePropertyChanged("SSDemographicsPractitioner5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsScrollFreeText1() As String
            Get
                Return Me.SSDemographicsScrollFreeText1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsScrollFreeText1Field, value) <> true) Then
                    Me.SSDemographicsScrollFreeText1Field = value
                    Me.RaisePropertyChanged("SSDemographicsScrollFreeText1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsScrollFreeText2() As String
            Get
                Return Me.SSDemographicsScrollFreeText2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsScrollFreeText2Field, value) <> true) Then
                    Me.SSDemographicsScrollFreeText2Field = value
                    Me.RaisePropertyChanged("SSDemographicsScrollFreeText2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsScrollFreeText3() As String
            Get
                Return Me.SSDemographicsScrollFreeText3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsScrollFreeText3Field, value) <> true) Then
                    Me.SSDemographicsScrollFreeText3Field = value
                    Me.RaisePropertyChanged("SSDemographicsScrollFreeText3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsScrollFreeText4() As String
            Get
                Return Me.SSDemographicsScrollFreeText4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsScrollFreeText4Field, value) <> true) Then
                    Me.SSDemographicsScrollFreeText4Field = value
                    Me.RaisePropertyChanged("SSDemographicsScrollFreeText4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsScrollFreeText5() As String
            Get
                Return Me.SSDemographicsScrollFreeText5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsScrollFreeText5Field, value) <> true) Then
                    Me.SSDemographicsScrollFreeText5Field = value
                    Me.RaisePropertyChanged("SSDemographicsScrollFreeText5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsTime1() As String
            Get
                Return Me.SSDemographicsTime1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsTime1Field, value) <> true) Then
                    Me.SSDemographicsTime1Field = value
                    Me.RaisePropertyChanged("SSDemographicsTime1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsTime2() As String
            Get
                Return Me.SSDemographicsTime2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsTime2Field, value) <> true) Then
                    Me.SSDemographicsTime2Field = value
                    Me.RaisePropertyChanged("SSDemographicsTime2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsTime3() As String
            Get
                Return Me.SSDemographicsTime3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsTime3Field, value) <> true) Then
                    Me.SSDemographicsTime3Field = value
                    Me.RaisePropertyChanged("SSDemographicsTime3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsTime4() As String
            Get
                Return Me.SSDemographicsTime4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsTime4Field, value) <> true) Then
                    Me.SSDemographicsTime4Field = value
                    Me.RaisePropertyChanged("SSDemographicsTime4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SSDemographicsTime5() As String
            Get
                Return Me.SSDemographicsTime5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSDemographicsTime5Field, value) <> true) Then
                    Me.SSDemographicsTime5Field = value
                    Me.RaisePropertyChanged("SSDemographicsTime5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Sex() As String
            Get
                Return Me.SexField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SexField, value) <> true) Then
                    Me.SexField = value
                    Me.RaisePropertyChanged("Sex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SocialSecurityNumber() As String
            Get
                Return Me.SocialSecurityNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SocialSecurityNumberField, value) <> true) Then
                    Me.SocialSecurityNumberField = value
                    Me.RaisePropertyChanged("SocialSecurityNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SocialSecurityNumber2() As String
            Get
                Return Me.SocialSecurityNumber2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SocialSecurityNumber2Field, value) <> true) Then
                    Me.SocialSecurityNumber2Field = value
                    Me.RaisePropertyChanged("SocialSecurityNumber2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SocialSecurityNumber3() As String
            Get
                Return Me.SocialSecurityNumber3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SocialSecurityNumber3Field, value) <> true) Then
                    Me.SocialSecurityNumber3Field = value
                    Me.RaisePropertyChanged("SocialSecurityNumber3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SocialSecurityNumber4() As String
            Get
                Return Me.SocialSecurityNumber4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SocialSecurityNumber4Field, value) <> true) Then
                    Me.SocialSecurityNumber4Field = value
                    Me.RaisePropertyChanged("SocialSecurityNumber4")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WebServiceResponse", [Namespace]:="http://tempuri.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WebServiceResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfirmationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Confirmation() As String
            Get
                Return Me.ConfirmationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConfirmationField, value) <> true) Then
                    Me.ConfirmationField = value
                    Me.RaisePropertyChanged("Confirmation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As Boolean
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org", ConfigurationName:="ClientDemWS.ClientDemographicsSoap")>  _
    Public Interface ClientDemographicsSoap
        
        'CODEGEN: Generating message contract since element name SystemCode from namespace http://tempuri.org is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WEBSVC.ClientDemographics.GetDictionaryItems", ReplyAction:="*")>  _
        Function GetDictionaryItems(ByVal request As ClientDemWS.GetDictionaryItemsRequest) As ClientDemWS.GetDictionaryItemsResponse
        
        'CODEGEN: Generating message contract since element name SystemCode from namespace http://tempuri.org is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WEBSVC.ClientDemographics.UpdateClientDemographics", ReplyAction:="*")>  _
        Function UpdateClientDemographics(ByVal request As ClientDemWS.UpdateClientDemographicsRequest) As ClientDemWS.UpdateClientDemographicsResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDictionaryItemsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDictionaryItems", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientDemWS.GetDictionaryItemsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientDemWS.GetDictionaryItemsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class GetDictionaryItemsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SystemCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String)
            MyBase.New
            Me.SystemCode = SystemCode
            Me.UserName = UserName
            Me.Password = Password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDictionaryItemsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDictionaryItemsResponse", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientDemWS.GetDictionaryItemsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientDemWS.GetDictionaryItemsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class GetDictionaryItemsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDictionaryItemsResult As ClientDemWS.ArrayOfDictionaryItemObjectDictionaryItemObject
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDictionaryItemsResult As ClientDemWS.ArrayOfDictionaryItemObjectDictionaryItemObject)
            MyBase.New
            Me.GetDictionaryItemsResult = GetDictionaryItemsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateClientDemographicsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateClientDemographics", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientDemWS.UpdateClientDemographicsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientDemWS.UpdateClientDemographicsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class UpdateClientDemographicsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SystemCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public ClientDemographicsInfo As ClientDemWS.ClientDemographicsObject
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public ClientID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String, ByVal ClientDemographicsInfo As ClientDemWS.ClientDemographicsObject, ByVal ClientID As String)
            MyBase.New
            Me.SystemCode = SystemCode
            Me.UserName = UserName
            Me.Password = Password
            Me.ClientDemographicsInfo = ClientDemographicsInfo
            Me.ClientID = ClientID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateClientDemographicsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateClientDemographicsResponse", [Namespace]:="http://tempuri.org", Order:=0)>  _
        Public Body As ClientDemWS.UpdateClientDemographicsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ClientDemWS.UpdateClientDemographicsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org")>  _
    Partial Public Class UpdateClientDemographicsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateClientDemographicsResult As ClientDemWS.WebServiceResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateClientDemographicsResult As ClientDemWS.WebServiceResponse)
            MyBase.New
            Me.UpdateClientDemographicsResult = UpdateClientDemographicsResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClientDemographicsSoapChannel
        Inherits ClientDemWS.ClientDemographicsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClientDemographicsSoapClient
        Inherits System.ServiceModel.ClientBase(Of ClientDemWS.ClientDemographicsSoap)
        Implements ClientDemWS.ClientDemographicsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ClientDemWS_ClientDemographicsSoap_GetDictionaryItems(ByVal request As ClientDemWS.GetDictionaryItemsRequest) As ClientDemWS.GetDictionaryItemsResponse Implements ClientDemWS.ClientDemographicsSoap.GetDictionaryItems
            Return MyBase.Channel.GetDictionaryItems(request)
        End Function
        
        Public Function GetDictionaryItems(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String) As ClientDemWS.ArrayOfDictionaryItemObjectDictionaryItemObject
            Dim inValue As ClientDemWS.GetDictionaryItemsRequest = New ClientDemWS.GetDictionaryItemsRequest()
            inValue.Body = New ClientDemWS.GetDictionaryItemsRequestBody()
            inValue.Body.SystemCode = SystemCode
            inValue.Body.UserName = UserName
            inValue.Body.Password = Password
            Dim retVal As ClientDemWS.GetDictionaryItemsResponse = CType(Me,ClientDemWS.ClientDemographicsSoap).GetDictionaryItems(inValue)
            Return retVal.Body.GetDictionaryItemsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ClientDemWS_ClientDemographicsSoap_UpdateClientDemographics(ByVal request As ClientDemWS.UpdateClientDemographicsRequest) As ClientDemWS.UpdateClientDemographicsResponse Implements ClientDemWS.ClientDemographicsSoap.UpdateClientDemographics
            Return MyBase.Channel.UpdateClientDemographics(request)
        End Function
        
        Public Function UpdateClientDemographics(ByVal SystemCode As String, ByVal UserName As String, ByVal Password As String, ByVal ClientDemographicsInfo As ClientDemWS.ClientDemographicsObject, ByVal ClientID As String) As ClientDemWS.WebServiceResponse
            Dim inValue As ClientDemWS.UpdateClientDemographicsRequest = New ClientDemWS.UpdateClientDemographicsRequest()
            inValue.Body = New ClientDemWS.UpdateClientDemographicsRequestBody()
            inValue.Body.SystemCode = SystemCode
            inValue.Body.UserName = UserName
            inValue.Body.Password = Password
            inValue.Body.ClientDemographicsInfo = ClientDemographicsInfo
            inValue.Body.ClientID = ClientID
            Dim retVal As ClientDemWS.UpdateClientDemographicsResponse = CType(Me,ClientDemWS.ClientDemographicsSoap).UpdateClientDemographics(inValue)
            Return retVal.Body.UpdateClientDemographicsResult
        End Function
    End Class
End Namespace
