//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTST.ScriptLinkService.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.ClientDischarge.cls")]
        public string NTST_ScriptLinkService_Web_ClientDischarge_ClientDischarge {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_ClientDischarge_ClientDischarge"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.UserManagement.cls")]
        public string NTST_ScriptLinkService_Web_UserManagement_WebServices {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_UserManagement_WebServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.DCIImport.cls")]
        public string NTST_ScriptLinkService_Web_DCIImport_DCIImport {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_DCIImport_DCIImport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.ClientDiagnosis.cls")]
        public string NTST_ScriptLinkService_Web_ClientDiagnosis_ClientDiagnosis {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_ClientDiagnosis_ClientDiagnosis"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.ProgramTransfer.cls")]
        public string NTST_ScriptLinkService_Web_ProgramTransfer_ProgramTransfer {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_ProgramTransfer_ProgramTransfer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WSAPI.PM.Appointment.AppointmentService." +
            "cls")]
        public string NTST_ScriptLinkService_Web_AppointmentService_Appointment {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_AppointmentService_Appointment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://avtest:8972/csp/avtest/hmhcpmlive/WEBSVC.AppointmentScheduling.cls")]
        public string NTST_ScriptLinkService_Web_AppointmentScheduling_AppointmentScheduling {
            get {
                return ((string)(this["NTST_ScriptLinkService_Web_AppointmentScheduling_AppointmentScheduling"]));
            }
        }
    }
}
